### ISSUE TITLE
Change default copy behaviour to --parents

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#107]
Not 100% sure about this, adding this here to track the issue.

Currently s5cmd flattens source directory hiearchy while downloading (cp/mv). For example:
```
s3://bucket/obj1
s3://bucket/obj2
s3://bucket/01/obj2
```

`s5cmd cp 's3://bucket/*' .`

The default behaviour is to find each object recursively, and download them while ignoring all prefixes after the wildcard. Result:

```
$ ls 

obj1
obj2
```

There'll be only 1 `obj2` but we're not very confident which one.

We should make --parents the default behaviour, and `--flatten` an option.

**Comment by jackwellsxyz** [comment]
I might also suggest making '-r' an alias for --parents, which would bring s5cmd cp more in line with standard UNIX cp behaviour.
