### ISSUE TITLE
Document 'Advanced Usage'

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#153]
An `Advanced Usage` section would be a nice addition to the Readme. It could contain;

- Piping to `s5cmd run`: a clever usage is documented at @joshuarobinson's [article](https://medium.com/@joshua_robinson/s5cmd-hits-v1-0-and-intro-to-advanced-usage-37ad02f7e895) (Thanks for the article! Again! 💯 )
- Suggest using wildcards if there are many objects to be deleted and they share a common pattern. For example, consider these objects;
```
s3://bucket/prefix/2020/03/object1.gz
s3://bucket/prefix/2020/04/object1.gz
````

Instead of removing like
```
s3://bucket/prefix/2020/03/object1.gz
s3://bucket/prefix/2020/04/object1.gz
````

Suggest:
```
s3://bucket/prefix/2020/0*/object*.gz
````

Using wildcard for removing many objects dramatically improves execution times (single request per 1000 objects) since s5cmd utilizes S3 Batch API.

**Comment by fbarotov** [comment]
Hi, thanks @igungor for the issue and suggestion. 

Regarding the remove operation example, I was wondering whether using wildcard makes a difference for this scenario or not. For

`rm s3://bucket/prefix/2020/0*/object*.gz`

it seems s5cmd iterates remote objects in the given bucket and for each object that matches the given pattern it sends a delete request to S3. 
*cost = listing objects in the bucket + 2 delete request*

however, if separate delete requests

`rm s3://bucket/prefix/2020/03/object1.gz`
`rm s3://bucket/prefix/2020/04/object1.gz`

are executed, s5cmd hands over those commands to S3. 
*cost = 2 delete request*

For deleting multiple objects, shouldn't the following two commands present same performance?

`s5cmd rm s3://bucket/pattern`
`s5cmd ls s3://bucket/pattern | grep -v DIR | awk '{print $NF}' | xargs -I {} echo "rm s3://bucket/{}" | s5cmd run`

thanks for your time :)

**Comment by igungor** [comment]
@fbarotov https://github.com/peak/s5cmd#delete-multiple-s3-objects

If you're handling thousands of objects, s5cmd sends  1 request per thousand objects. That makes the perf gain of using wildcard more apparent.
