### ISSUE TITLE
I can't install s5cmd in a Windows machine

### ISSUE THREAD

**Issue by asotos87** [peak/s5cmd#154]
I can't install s5cmd in my Windows machine. I don't have experience with Go, so for me is little bit hard.
Once I run the command go get github.com/peak/s5cmd should I run something else?
It doesn't work in my machine.I use the last version of Go.

**Comment by igungor** [comment]
We don't provide executables for Windows environment becasue we haven't fully tested `s5cmd` on Windows.

As for `go get`, `s5cmd` binary should be at `bin\s5cmd` relative to your home folder.

**Comment by Timbus** [comment]
The previous release of s5cmd works, 1.0.0 introduced the rlimit syscall for a linux-specific issue: #131 

I'm not sure how Go does conditional compilation, but I'm sure its not too difficult to exclude that code on a windows compile.

To be clear: I don't want to use windows, but sometimes have to =/.
