### ISSUE TITLE
Add 'Why s5cmd' section to README

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#164]
We should keep a list of
- why this tool is written and why we think it's awesome
- why people should prefer it over awscli
- written articles about `s5cmd`. [1](https://aws.amazon.com/blogs/opensource/parallelizing-s3-workloads-s5cmd/), [2](https://medium.com/@joshua_robinson/s5cmd-for-high-performance-object-storage-7071352cc09d), [3](https://medium.com/@joshua_robinson/s5cmd-hits-v1-0-and-intro-to-advanced-usage-37ad02f7e895)

**Comment by seruman** [comment]
Closed by: #164
