### ISSUE TITLE
cp arguments

### ISSUE THREAD

**Issue by jakeman0527** [peak/s5cmd#166]
Should the following options be combined?
```
--if-size-differ
--if-source-newer
```

For example if I pass `--if-size-differ` and destination file size is different from source the file will be copied.

But if I also add `--if-source-newer` and timestamp is the same on both source and destination the file will not be copied.

Looking at the shouldOverride function
[https://github.com/peak/s5cmd/blob/master/command/cp.go#L452-L502](https://github.com/peak/s5cmd/blob/master/command/cp.go#L452-L502)

`--if-source-newer` if passed will always override `--if-size-differ`

**Comment by igungor** [comment]
These options are 2 distinct controls for overriding the destination file. They can't be combined.

> But if I also add `--if-source-newer` and timestamp is the same on both source and destination the file will not be copied.

Correct. Do you want them to work together? If so, could you share a use case please? I don't think we'd change the current behaviour though since we stabilized the 1.x branch.

**Comment by igungor** [comment]
Closing the issue.
