### ISSUE TITLE
Wildcard mv causes infinite repetition if target destination also qualifies wildcart

### ISSUE THREAD

**Issue by rkrn** [peak/s5cmd#168]
Suppose you have objects like this:
```
...
s3://sandbox/single-4k.blob.4
s3://sandbox/single-4k.blob.5
s3://sandbox/single-4k.blob.6
...
s3://sandbox/single-16k.blob.1
s3://sandbox/single-16k.blob.2
...
```
Trying to move them to a new prefix that also matches the glob causes infinite repetition. For example:
```
s5cmd mv 's3://sandbox/single*.blob*' s3://sandbox/single/
```
Produces this after some time:
```
...
mv s3://sandbox/single/single/single/single-4k.blob.1 s3://sandbox/single/single/single/single/single-4k.blob.1
...
```
Naive solution is to have the application make a full pass of the bucket for keys matching the wildcard, keep state of the initial list of qualified keys, and pop them off the queue as the individual `mv`s complete. I am guessing that right now it is doing a lazy evaluation of qualified keys one at a time.

For others who are experiencing this, temporary workaround right now is to pipe a `s5cmd ls` wildcard output into `xargs` and individually `s5cmd mv`.

**Comment by sonmezonur** [comment]
@rkrn Thanks for reporting this. Could you please share the version of s5cmd and the OS you are using? I could not reproduce the issue. It would be helpful if you can share step-by-step repro and complete bucket hierarchy (including other prefixes).
