### ISSUE TITLE
How can I list the contents of public bucket anonymously, without Access Key and Secret Key?

### ISSUE THREAD

**Issue by emres** [peak/s5cmd#172]
Hello,

When using `aws cli`, I can read (e.g. the list the contents of) a **publicly** available bucket **anonymously**:

`$ aws --no-sign-request s3 ls s3://commoncrawl/cc-index/table/cc-main/warc/`

When I tried a similar command line for `s5cmd` it didn't work:

```
$ ./s5cmd --no-sign-request ls s3://commoncrawl/cc-index/table/cc-main/warc/
Incorrect Usage. flag provided but not defined: -no-sign-request
```

The following didn't work, too:

```
$ ./s5cmd ls s3://commoncrawl/cc-index/table/cc-main/warc/
ERROR "ls s3://commoncrawl/cc-index/table/cc-main/warc/": InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records. status code: 403, request id: 6E3594576FF1D10E, host id: 7OAlP1Iwhw6rtlUW6RtKlDmko8NuEGHsc8aBrTSvBpnsfYLfq2Ueh9Z/CRTWjbw+FyrT09qXv2s=
```

I tried the following, too, without succeeds:

```
$ ./s5cmd ls s3://anonymous@commoncrawl/cc-index/table/cc-main/warc/
ERROR "ls s3://anonymous@commoncrawl/cc-index/table/cc-main/warc/": InvalidBucketName: The specified bucket is not valid. status code: 400, request id: 443F9003CEF0FD3E, host id: AcV1+lpkgkzREsmqyI6uPmHp5nH6UcHbZwpzSPGF7eAh2vEX2C1ijQrNjFIZ52BRGO79g3udPWI=
```

How can I access a publicly available bucket anonymously? That is, without an Access Key Id and Secret Access Key (which is possible when I use `aws cli`).

My `s5cmd` version is:

```
$ ~/bin/s5cmd version
v1.0.0-391e9cc
```

and the `aws cli` version that works:

```
$ aws --version
aws-cli/2.0.17 Python/3.7.3 Linux/5.3.0-45-generic botocore/2.0.0dev21
```

**Comment by igungor** [comment]
Hi,

There's no anonymous credentials support, sorry.

> The following didn't work, too:
> 
> ```
> $ ./s5cmd ls s3://commoncrawl/cc-index/table/cc-main/warc/
> ERROR "ls s3://commoncrawl/cc-index/table/cc-main/warc/": InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records. status code: 403, request id: 6E3594576FF1D10E, host id: 7OAlP1Iwhw6rtlUW6RtKlDmko8NuEGHsc8aBrTSvBpnsfYLfq2Ueh9Z/CRTWjbw+FyrT09qXv2s=
> ```

Not sure why but this works for me. I have a profile set to access private buckets, so my requests to the below bucket are signed:

```
$ s5cmd ls s3://commoncrawl/cc-index/table/cc-main/warc/

2020/06/08 23:01:14 DEBUG: Request s3/ListObjectsV2 Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /?delimiter=%2F&list-type=2&prefix=cc-index%2Ftable%2Fcc-main%2Fwarc%2F HTTP/1.1
Host: commoncrawl.s3.amazonaws.com
User-Agent: aws-sdk-go/1.29.14 (go1.14.2; darwin; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED
X-Amz-Content-Sha256: REDACTED
X-Amz-Date: 20200608T200114Z
X-Amz-Security-Token: REDACTED
Accept-Encoding: gzip

        DIR crawl=CC-MAIN-2013-20/
        DIR crawl=CC-MAIN-2013-48/
        DIR crawl=CC-MAIN-2014-10/
        DIR crawl=CC-MAIN-2014-15/
        DIR crawl=CC-MAIN-2014-23/
        DIR crawl=CC-MAIN-2014-35/
                   ...
```

**Comment by emres** [comment]
Thanks for the detailed and clear explanation. My case is a bit of an anomaly, in the sense that I'm running s5cmd primarily against a non-standard object store (i.e. not AWS or GCP, something in our data center that is S3-compatible to a large extent). Apparently, as long as your Access Key Id is provided by AWS, you can access a publicly available bucket (which isn't my case because the Access Key Id is provided by the proprietary object storage system). 

Lack of `aws cli`-like `--no-sign-request` is not a showstopper for me at the moment, but rather something nice to have. Thanks again for `s5cmd`! I'm closing this issue.

**Comment by igungor** [comment]
Hello @emres. I wanted to let you know that access to public buckets is supported now with https://github.com/peak/s5cmd/pull/305

It's available on master branch.

**Comment by emres** [comment]
Thanks a lot for pinging me about this feature implementation! 🙏
