### ISSUE TITLE
What's the expected output of --log verbose (seems like it has no effect)?

### ISSUE THREAD

**Issue by emres** [peak/s5cmd#173]
Hello,

What's the expected output of  `--log verbose`? The reason I'm asking is because I run the same command with and without `--log verbose`, but there's no difference in the output. E.g. both commands return the same output:

`s5cmd --log verbose ...`
`s5cmd ...`

Am I passing the value `verbose` in a wrong format?

**Comment by sonmezonur** [comment]
Hi,

I think the help text is not up to date. Currently, there is no `verbose` option. We changed it to `debug` in the latest release. And it is only used for printing [warning logs](https://github.com/peak/s5cmd/blob/2d45404136d4742c79b5d5e640d8659397a55a08/error/error.go#L83) of copy operations.
```
  --no-clobber, -n
  --if-size-differ, -s
  --if-source-newer, -u
```

**Example:** If you enable `debug` option and provide `--no-clobber` flag to your copy command, you may get a debug message indicating that object already exists.

```
s5cmd --log=debug cp --no-clobber test.txt s3://bucket/test.txt # assume you already have test.txt
DEBUG "cp test.txt s3://bucket/test.txt": object already exists
```

We need to fix the usage text of `log` flag. If you are interested, you may submit a PR to resolve this issue. Thanks :)
