### ISSUE TITLE
Windows filepath backslashes are not converted when uploaded to S3 recursively

### ISSUE THREAD

**Issue by mrekim0** [peak/s5cmd#178]
I created a windows binary as of fce1e2a, and noticed that the filepath retains the backslash when recursively copying to S3, which means the S3 folder keys separators are not parsed as folders.

This occurs in Windows 10 and in Cygwin, even with unix paths

**Example:**

**Folder contents**

```
d:\workspace
   |_dev
      |_foldera
         |_file.txt
```

`s5cmd cp d:\workspace\dev s3://mybucketname/`

**Expected result:**

`cp d:\workspace\dev\foldera\file.txt s3://mybucketname/dev/foldera/file.txt`

**Actual Result:**

`cp d:\workspace\dev\foldera\file.txt s3://mybucketname/dev\foldera\file.txt`

**Comment by igungor** [comment]
https://github.com/peak/s5cmd/pull/181 should fix this issue.
