### ISSUE TITLE
Question about du implementation

### ISSUE THREAD

**Issue by shashank88** [peak/s5cmd#179]
Hi, I am not super familiar with go, but how does du work with s5cmd? Do you launch goroutines, each doing a HEAD request and then getting the ContentLength from the response for each element of a iteration in S3?
I was looking at https://github.com/peak/s5cmd/blob/master/command/du.go but didn't spot any goroutines being spawned here.

**Comment by shashank88** [comment]
@igungor maybe?

**Comment by igungor** [comment]
Hi @shashank88,

> Do you launch goroutines, each doing a HEAD request and then getting the ContentLength from the response for each element of a iteration in S3?

https://github.com/peak/s5cmd/blob/master/storage/s3.go#L136

Fortunately ListObjectsV2 request to S3 will return object sizes, sending HEAD for each object is not necessary.

**Comment by shashank88** [comment]
It does 😮 , that makes my life so much easier! Thanks a lot for the response and making this useful project!
