### ISSUE TITLE
Support for kms encryption?

### ISSUE THREAD

**Issue by lyle-nel** [peak/s5cmd#18]
In the vanilla aws cli, one would copy objects that are encrypted with a kms key as follows:
`aws s3 cp s3://foo s3://bar --sse aws:kms`

Is there something equivalent in s5cmd? Or does the tool currently not support encryption?

PS
This is an amazing tool, especially the auto-completion functionality!

**Comment by igungor** [comment]
Hi @lyle-nel 

`s5cmd` has no support for KMS unfortunately.
