### ISSUE TITLE
Global options and "Run multiple commands in parallel" feature don't mix

### ISSUE THREAD

**Issue by emres** [peak/s5cmd#191]
Hello,

I'm using version `v1.0.0-391e9cc` of s5cmd and I've realized that global options and "[Run multiple commands in parallel](https://github.com/peak/s5cmd#run-multiple-commands-in-parallel)" feature don't mix.

My example commands.txt:

```
$ cat ~/code/s3bench/commands.txt
cp ~/code/s3bench/data/1000_small_files_01/ s3://bucket001-benchmark/
cp ~/code/s3bench/data/1000_small_files_02/ s3://bucket001-benchmark/

```

Trying to run this against the [Nutanix Object Store](https://www.nutanix.com/en) that I'm using gives the following error:

```
$ cat ~/code/s3bench/commands.txt | s5cmd --no-verify-ssl --endpoint-url https://example.com run
...
ERROR "cp ~/code/s3bench/data/1000_small_files_01/ s3://bucket001-benchmark/": given object not found
```

But if I try one of the commands manually, it runs perfectly fine, as in:

`s5cmd --no-verify-ssl --endpoint-url https://example.com  cp ~/code/s3bench/data/1000_small_files_01/ s3://bucket001-benchmark/
`

How can I apply the same global options to the multiple parallel runs of s5cmd commands?

**Comment by sonmezonur** [comment]
Hello,

When you run `s5cmd cp ~/code/...`, shell assigns the expanded value of `~` to the given command. But if you prefer using run mode,  you need to give a full path since shell expansion doesn't work.

Could you please try it by giving an absolute path for your source files? Like:

```
cp /Users/onur/code/s3bench/data/1000_small_files_01/ s3://bucket001-benchmark/
cp /Users/onur/code/s3bench/data/1000_small_files_02/ s3://bucket001-benchmark/
```

Thanks

**Comment by emres** [comment]
Thanks for the quick reaction! Indeed, when I've expanded `~` manually in `commands.txt` to **my home directory**, it worked as expected. 

Adding a small explanation to the existing error message (i.e. indicating that the problem might be related to shell/`~` expansion), might enhance the UX of this already great utility. (Adding the same information to the documentation would be also good, but keep it'll be a little further away from the error message, therefore a little less useful).
