### ISSUE TITLE
Add option to cp to stdout

### ISSUE THREAD

**Issue by fiendish** [peak/s5cmd#20]
aws s3 cp has a magic "-" option which, on linux and macos at least, works like writing to /dev/stdout. s5cmd does not look like it supports providing an in-order stream of bytes (writing to stdout or a fifo fails because they don't allow seeking). 

Example use case: We would like to be able to pipe extremely large files (terabytes) from s3 into another program such as sha512sum without writing it to disk or storing the entire file in RAM.

**Comment by thecooltechguy** [comment]
Hi, will this be supported by s5cmd?

**Comment by igungor** [comment]
We decided to go with the `cat` subcommand instead of magic `-` character that indicates stdin/stdout. It's been there since v1.0.0.

**Comment by thecooltechguy** [comment]
Oh ok got it @igungor , do you by chance know why `aws s3 cp s3://bucket/abc.tar -` is a lot faster than s5cmd's cat? Is it due to some intentional design choice by s5cmd for this cat operation?

**Comment by igungor** [comment]
Writing to stdout requires data order guarantee (otherwise data will be corrupt), it needs to be done in a synchronous and sequential way.

I'm guessing awscli downloads the object using parallel future tasks, orders them, and writes to stdout sequentially. s5cmd doesn't do that for `cat`.
