### ISSUE TITLE
when object is restored from glacier, cant download it.

### ISSUE THREAD

**Issue by s4mur4i** [peak/s5cmd#206]
We restored some items from glacier, and wanted to download it (console allows download)
But s5cmd throws error because of:
https://github.com/peak/s5cmd/blob/601ee14f130b21739c4c315218ccdfb71ac41afa/command/cp.go#L248

**Comment by s4mur4i** [comment]
aws s3 sync for example has option `--force-glacier-transfer` which omits checks for glacier. maybe we should add similar option.

**Comment by ocakhasan** [comment]
hey @s4mur4i, I tried to create the same issue, but in my case, the object (restored from glacier) is downloaded. Can you please check and let me know if you have the same issue still?

**Comment by gusostow** [comment]
Is it intended that restored glacier objects will copy as single objects, but will fail a wildcard copy without the `--force-glacier-transfer` flag?
