### ISSUE TITLE
"Mirroring" should prune files at the destination not found at source

### ISSUE THREAD

**Issue by chipzoller** [peak/s5cmd#213]
There either needs to be a switch in the `cp` command to prune files at the destination not found at the source, or the existing behavior should be altered to more accurately reflect how "mirroring" is defined. When a directory is "mirrored" to a target directory, that means at the end of the operation, the two should be identical. With s5cmd using the `-n -s -u` switches does not produce this result and only adds files not found at the target.

**Comment by chipzoller** [comment]
When using the term "mirroring" I'm referring to the help for `s5cmd cp`:

```
09. Mirror a directory to target S3 prefix
     > s5cmd cp -n -s -u dir/ s3://bucket/target-prefix/

10. Mirror an S3 prefix to target S3 prefix
    > s5cmd cp -n -s -u s3://bucket/source-prefix/* s3://bucket/target-prefix/
```

**Comment by chipzoller** [comment]
Any comment on this or?

**Comment by igungor** [comment]
You're right. The wording of "mirror" is incorrect in this context. We should change it to something more accurate.

**Comment by chipzoller** [comment]
Alternatively, add an action "mirror" option that performs mirroring.

**Comment by igungor** [comment]
Mirroring (or sync) is requrested before at #3.
