### ISSUE TITLE
Retry on "connection reset by peer"

### ISSUE THREAD

**Issue by eminugurkenar** [peak/s5cmd#225]
We noticed that while uploading singile big files we receive 

` RequestError: send request failed caused by: Put https://xxx/aaa/bbb/ccc?partNumber=318&uploadId=idasdsadasda--: read tcp 10.xx.xx.xx:39538->52.217.32.12:443: read: connection reset by peer`  

We think it is better to retry ?

**Comment by igungor** [comment]
Yes. https://github.com/aws/aws-sdk-go/issues/2737.

**Comment by donovanbai** [comment]
I'm still seeing this error on latest commit. Seems like the fix was reverted in https://github.com/peak/s5cmd/commit/6abfea8244c83e5476bb13fc68eacddae1a84e7f# ?
