### ISSUE TITLE
Will not install on Windows Server

### ISSUE THREAD

**Issue by doit-mattporter** [peak/s5cmd#228]
Hi,

I'm looking to help an on-prem company migrate into the cloud which will involve uploading of a large number of files to buckets. They have Windows servers with TBs of data to be moved up which could be sped up by this tool, however installing it via 'go.exe get' does not succeed, whereas the equivalent Linux machine commands work fine. Using Powershell:

```
# Install s5cmd
C:\Go\bin\go.exe get github.com/peak/s5cmd
PS D:\> go.exe get github.com/peak/s5cmd
github.com/peak/s5cmd/log/stat
C:\Users\your_username\go\src\github.com\peak\s5cmd\log\stat\stat.go:87:14: undefined: strings.Builder
github.com/peak/s5cmd/vendor/github.com/urfave/cli/v2
C:\Users\your_username\go\src\github.com\peak\s5cmd\vendor\github.com\urfave\cli\v2\fish.go:74:18: undefined: strings.Builder
C:\Users\your_username\go\src\github.com\peak\s5cmd\vendor\github.com\urfave\cli\v2\fish.go:123:18: undefined: strings.Builder
C:\Users\your_username\go\src\github.com\peak\s5cmd\vendor\github.com\urfave\cli\v2\fish.go:160:45: undefined: strings.Builder
github.com/peak/s5cmd/storage
C:\Users\your_username\go\src\github.com\peak\s5cmd\storage\s3.go:739:5: undefined: errors.As
C:\Users\your_username\go\src\github.com\peak\s5cmd\storage\s3.go:746:5: undefined: errors.As
C:\Users\your_username\go\src\github.com\peak\s5cmd\storage\s3.go:760:5: undefined: errors.As
```

**Comment by igungor** [comment]
Hi @doit-mattporter 

By looking at the logs, your Go version seems to be old. `s5cmd` requires at least Go 1.13. Yours is likely pre Go 1.10. Please upgrade your installation. We also provide Windows binaries that may help you avoid compiling the project.

I'm going to close the issue. If you have any questions, please feel free to repoen the issue. Thanks.
