### ISSUE TITLE
Using multiple credentials with s5cmd

### ISSUE THREAD

**Issue by rsomu** [peak/s5cmd#229]
I am using s5cmd to connect to two S3 on-premises object storage (FlashBlade) and the only way I can connect is by setting the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and cannot use the .aws/credentials file as s5cmd doesn't seem to take any profile option.  Can this be implemented?

**Comment by seruman** [comment]
You're right, it does not. Since it uses AWS SDK for Go, with `AWS_PROFILE` set to your desired profile `s5cmd` should use it.

**Comment by igungor** [comment]
@rsomu Have you tried changing your settings with `AWS_PROFILE` environment variable like @seruman said? I'm using multiple AWS profiles with s5cmd without an issue.

**Comment by igungor** [comment]
Closing this one. If you think the solution above doesn't work you, please feel free to re-open the issue.
