### ISSUE TITLE
Support for signature v2

### ISSUE THREAD

**Issue by kemege** [peak/s5cmd#236]
I did not find any documentation about this, but from the source code files, it seems that only signature verion 4 is supported in s5cmd.
Is signature v2 going to be supported in the future? Since for some S3-compitable storage services, v2 is well supported, but v4 is not.

**Comment by igungor** [comment]
Hi @kemege. SigV2 is not in our agenda unfortunately. We focus on a better S3 support in terms of performance and flexibility.
