### ISSUE TITLE
NoCredentialProviders: no valid providers in chain - Backblaze

### ISSUE THREAD

**Issue by milekz** [peak/s5cmd#237]
I follow https://help.backblaze.com/hc/en-us/articles/360047171694-How-to-use-s5cmd-with-B2

setup is done @  ~/.aws/credentials

But i always get this error  ( s3cmd - with same credentials work ) 
In firewall log i don't see any attempts to connect to s3.eu-central-003.backblazeb2.com ....

`# ./s5cmd  --endpoint-url https://s3.eu-central-003.backblazeb2.com ls

ERROR "ls ": NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors
`

**Comment by andryan** [comment]
Are you using v1.2.0?  Try downgrading to v1.1.0.

I am getting a different error every time I do ls on the content of my B2 Backblaze buckets, but just ls (listing bucket) works.  None of the operation commands work either.  Always getting 403.

**Comment by igungor** [comment]
@milekz hello. Just wanted to iterate @andryan's question.

1.2.0 introduced a bug that affects s3-compatible services. A fix is in progress. Meanwhile, could you try using 1.1.0 and see if it works for you?

**Comment by igungor** [comment]
New release (v1.2.1) is published. We've tested for Backblaze (and a few S3-compatible services too) and worked without a problem.

I'm closing the issue. Please reopen if you're still experiencing the same problem with the latest release.

**Comment by shoce** [comment]
I experience the same issue with DigitalOcean Spaces with both the latest release and the latest master

**Comment by szeitlin** [comment]
I'm getting the same error with v2.1.0-beta.1-3e08061 on linux trying to connect to oracle cloud, which is strange since I was able to get it to work just fine on OS X. I'm wondering if I also need the aws CLI installed or something-? I had a pre-existing .aws/credentials and config on my mac, but I don't have that on the linux machine.
