### ISSUE TITLE
s5cmd slow startup

### ISSUE THREAD

**Issue by raz-adroll** [peak/s5cmd#244]
Hi,

I noticed that using s5cmd was slow for me, doing a simple `s5cmd ls` would take ~20 seconds to start.

I decided to look into and I found why s5cmd was so slow when it ran in my machine, but ran ok in an ec2 instance, well, turns out that by default has a retry of 10 requests. Doing `s5cmd -r 0 ls` would actually be fast.

After some digging, I found out that it would make 10 requests (throttling included) for getting the credentials. So, it would make 10 calls to `169.254.169.254/latest/api/token` and then fallback to `169.254.169.254/latest/meta-data/iam/security-credentials/`

Then I Google similar issues and I got this: https://github.com/aws/aws-sdk-go/issues/2972

Maybe it should have a less aggressive retry for getting tokens?

**Comment by arl** [comment]
In certain use cases this makes `s5cmd` unusable.
Now that I've understood the problem and aliased `s5cmd` to `s5cmd -r 0` I can switch to `s5cmd` back from `aws s3`, again.

**Comment by tomberek** [comment]
Yes, ran into this when using mock credential providers.

Another referencing issue about the endpoint: https://github.com/aws/aws-sdk-go/issues/2972

**Comment by bartek-siudeja** [comment]
It seems I still need `-r 0` to speed up start on s5cmd `v1.4.0-d7a0dda`.

**Comment by strophy** [comment]
This issue occurs when running s5cmd in a Docker container on an EC2 instance due to the hop limit of 1 on requesting the EC2Metadata. The correct way to resolve it is to set `http_put_response_hop_limit = 2` in the instance metadata. 

Reference: https://github.com/aws/aws-sdk-go/issues/2972#issuecomment-747781100
