### ISSUE TITLE
How to skip only on "no object found" error?

### ISSUE THREAD

**Issue by vroad** [peak/s5cmd#253]
Both file not found error and API error (such as AccessDenied) will cause s5cmd to exit with status 1.
How to check if directory exists without parsing command output, or skip only "no object found" error?

There is no sync command, and cp will fail as well if directory does not exist.

```
aws-vault exec admin -- s5cmd ls s3://my-bucket/status/*
ERROR "ls s3://my-bucket/status/*": no object found
aws-vault: error: exec: Failed to wait for command termination: exit status 1
``` 

```
aws-vault exec test-profile -- s5cmd ls s3://my-bucket/status/*
ERROR "ls s3://my-bucket/status/*": AccessDenied: Access Denied status code: 403, request id: <hidden>, host id: <hidden>
aws-vault: error: exec: Failed to wait for command termination: exit status 1
```

**Comment by igungor** [comment]
There's no distinct error codes to indicate different error types. Not sure if it'll help but there's a global `--json` flag that enables structured logging.
