### ISSUE TITLE
Required write permission to upload file

### ISSUE THREAD

**Issue by InvisibleMan1306** [peak/s5cmd#258]
### Steps to Recreate 

```bash
➜ ll ~/Temp/foo.txt
-rw-r--r-- 14:31 /Users/vkrylov/Temp/foo.txt
➜ s5cmd --log error cp --sse aws:kms ~/Temp/foo.txt s3://some-bucket-name/some-prefix/
➜ chmod -w ~/Temp/foo.txt
➜ ll ~/Temp/foo.txt
-r--r--r-- 14:31 /Users/vkrylov/Temp/foo.txt
➜ s5cmd --log error cp --sse aws:kms ~/Temp/foo.txt s3://some-bucket-name/some-prefix/
ERROR "cp /Users/vkrylov/Temp/foo.txt s3://some-bucket-name/some-prefix/foo.txt": open /Users/vkrylov/Temp/foo.txt: permission denied
```

### Problem
It seems like you should be able to upload files to S3 with just read permission enabled. Is there a reason why s5cmd needs write permission?

**Comment by igungor** [comment]
Thank you for the details @InvisibleMan1306 

This looks like an oversight. `s5cmd` doesn't need write bit for uploads. We'll take a look.

**Comment by InvisibleMan1306** [comment]
@igungor Thank you so much for fixing the issue and merging to master. I was wondering what your procedure for pushing new versions of s5cmd for brew and [docker hub](https://hub.docker.com/r/peakcom/s5cmd)?

**Comment by igungor** [comment]
> @igungor Thank you so much for fixing the issue and merging to master.

Cheers

>  I was wondering what your procedure for pushing new versions of s5cmd for brew and [docker hub](https://hub.docker.com/r/peakcom/s5cmd)?

We try to cut releases every month or so. Once a new release is created, brew and docker artifacts are automatically generated.
