### ISSUE TITLE
Add option for ACL on cp command

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [peak/s5cmd#26]
Hey!

Awesome work! This is super fast.

Can you add an option for --acl bucket-owner-full-control when using cp please?

Cheers!
Josh

**Comment by JoshuaEdwards1991** [comment]
I've created this as a hack around this functionality at the moment.

`AWS_REGION=eu-west-1 s5cmd ls s3://bucket-name/key/* | awk -v AWS_BUCKET="bucket-name" -v KEY="key" '{ printf "aws s3api put-object-acl --access-control-policy file://access_policy.json --bucket %s --key %s/%s\n", AWS_BUCKET, KEY, $5 }' | parallel -v -j 64`

This will update the ACL's in parallel making use of the `s5cmd ls` speed.

**Comment by igungor** [comment]
> Hey!

Hey @JoshuaEdwards1991 

> Awesome work! This is super fast.

Thanks!

> Can you add an option for --acl bucket-owner-full-control when using cp please?

Sorry for the late reply. S3 supports too many controls over the stored objects. Generally, we implement what we need and setting an `ACL` was not one of them (yet).

We'll take a look if we need anything else if we implement ACL parameter family.
