### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by sheldonhull** [peak/s5cmd#260]
`foobar.bak The process cannot access the file because it is being used by another process.`

This is causing an error with using to synchronize database backups via a job.
I'd like a way to make this informational so any locked files can just be bypassed till the next sync job. Is this possible?

This is being run in a Windows environment where the file isn't yet finished being created. The file is in the middle of creation and results in this lock temporarily.

**Comment by igungor** [comment]
There's a global `--json` flag. It's possible to parse json output and search for a specific string. I'm not sure if there's a better way.
