### ISSUE TITLE
Parallel download starts fast, and then slows down

### ISSUE THREAD

**Issue by thecooltechguy** [peak/s5cmd#263]
Hi,

We have a large dataset on S3 (~6+ TB) consisting of ~1.1M+ files, and we try to use s5cmd to download this dataset to a large ec2 instance's local NVME ssd disk (the new p4d instance, which has 400-gigabit networking).

When starting s5cmd's cp operation, initially the copying is very fast and all 96 of the cpu cores are fully utilized and the download data transfer happens at a fast rate. However, within ~30 seconds, suddenly the download slows down to a much slower rate and the cpu usage across all cores drops to nearly 0. 

So, we were confused as to why s5cmd's parallel download operation starts off fast and then immediately slows down after a few seconds.

Is this intentional, or is this due to some sort of throttling or another type of limitation?

Thanks!

**Comment by thecooltechguy** [comment]
Just want to add that this was due to an incorrect disk configuration that was maxing out IO and causing the download to slow down, nothing to do with s5cmd.

**Comment by igungor** [comment]
Good to know. Thanks.
