### ISSUE TITLE
How to add custom metadata e.g "cache-control"?

### ISSUE THREAD

**Issue by rioastamal** [peak/s5cmd#264]
Official AWS CLI does support adding metadata such as `--content-type` and `--cache-control`. 

```
$ aws s3 sync ./mydir/ s3://example-bucket/mydir/ \
--content-type 'application/rss+xml; charset=UTF-8' \
--cache-control 'max-age=86400'
```

The reason I need custom metadata is because I use S3 as static website hosting which sits behind Cloudfront. Setting correct origin headers such as `cache-control` and `content-type` for CDN/Proxy is important to my case.

How do I add custom metadata when uploading object using s5cmd? It seems I did not find the options.

**Comment by igungor** [comment]
Hi @rioastamal, there's no `cache-control` support yet. `content-type` is inferred from the file extension and file content automatically, you can't change it manually.

**Comment by rioastamal** [comment]
Hi @igungor, is there any plan to add custom metadata feature in the near future? I really like to use s5cmd because it's faster but that's the only one that blocking me to use it in production.

**Comment by nattofriends** [comment]
(Looks like Cache-Control support was added in #318)
