### ISSUE TITLE
Wasabi `ls` includes parent dir

### ISSUE THREAD

**Issue by JeffreyShran** [peak/s5cmd#265]
Command `s5cmd --endpoint-url=https://s3.eu-central-1.wasabisys.com ls s3://data/programs/`

Returns the "programs" directory as if it was a child.

If the folder structure is:
```
s3://data/programs/
s3://data/programs/subfolder1
s3://data/programs/subfolder2
```

e.g 
```
    ...
    DIR subfolder1
    DIR subfolder2
    DIR programs
```

I would expect only:
```
    ...
    DIR subfolder1
    DIR subfolder2
```

**Comment by igungor** [comment]
On S3 and many other S3-compatible services, target "directory" is not printed. I'm not sure what Wasabi returns for ListObjectsV2 API request. 

Have you tried with `awscli` or other s3 tools?

**Comment by igungor** [comment]
No feedback. Please feel free to reopen the issue if you could provide more information.
