### ISSUE TITLE
Trailing slash for recursive cp

### ISSUE THREAD

**Issue by echan5** [peak/s5cmd#267]
Hi, it took me a while to figure out why `s5cmd cp` was erroring when I was running it on a directory of files. It turns out that a trailing slash is required for the target path - for e.g. `s5cmd cp /home/mydirectory s3://mybucket/some/prefix` errors, but `s5cmd cp /home/mydirectory s3://mybucket/some/prefix/` works. This behaviour is different from awcli's `s3 cp --recursive` (it doesn't matter whether you have a trailing slash or not on the target). 

Would be possible to either: 
1) make it work even when there's no trailing slash (probably ideal?), or 
2) add documentation around the requirement for a trailing slash (if the other is too difficult to implement)?

Thank you!

**Comment by igungor** [comment]
s5cmd is 100% compatible with awscli in terms of path arguments. s5cmd supports wildcards so a trailing slash changes the meaning of the destination path.

Actually it's documented: https://github.com/peak/s5cmd#upload-multiple-files-to-s3
