### ISSUE TITLE
How can I reduce the cpu usage on copy command?

### ISSUE THREAD

**Issue by sheldonhull** [peak/s5cmd#268]
I'm using S5 command to "sync" a local directory of backup files up to S3. It's performant and works great...a bit too great 😆.

Because this is a database server I'd like to make sure that the CPU of non-database processes stays minimal even if it means the backup job takes a little bit longer to sync. I tried reducing the concurrent count but it didn't make much of a difference. Right now on my server I get a spike of 90 to 100% CPU until the job is done.

It's really fast but I'm hoping there's some way to throttle this down so I can continue to use it but in sure it doesn't cause excessive resources to be taken away from the most important process on the server.

Any ideas?

**Comment by igungor** [comment]
s5cmd tries to utilize all cores by parallelizing the work. High CPU usage is expected if there are many files, low part-size and high concurreny options. If concurrency options don't work for you, It's best to use s5cmd behind a CPU limiter depending the environment it works on, such as `cpulimit` on Linux.
