### ISSUE TITLE
Backblaze b2 doesn't work

### ISSUE THREAD

**Issue by worldofpeace** [peak/s5cmd#269]
I attempted to use the `ls` command and got this ERROR

```
ERROR "ls ": InvalidAccessKeyId: The key '[redacted]' is not valid status code: 403, request id: [redacted], host id: [redacted]
```

but I've used other cli applications and didn't get an InvalidAccessKeyID error? Including, `backblaze-b2`, `goofys`, and `s3fs`.

**Comment by sonmezonur** [comment]
Hi @worldofpeace . Which version of  `s5cmd` are you using? Has this worked for earlier versions?

**Comment by worldofpeace** [comment]
1.1.0. I haven't tried any older versions.

**Comment by igungor** [comment]
Could you share the exact command please?

**Comment by igungor** [comment]
If you could provide a reproducer, I'll be happy to investigate the problem. I'm closing it now but please feel free to reopen the issue if you could provide us more information.

**Comment by igungor** [comment]
Thanks for the reproducer @fishdust. 

The documentation you shared says that endpoint is `us-west-002`, but the bucket I just created for testing says the endpoint is `us-west-000`.

See the `--endpoint-url` values:
```
s5cmd git:master Δ AWS_PROFILE=backblaze s5cmd --endpoint-url https://s3.us-west-002.backblazeb2.com ls
ERROR "ls": InvalidAccessKeyId: The key '00005329cf349a40000000001' is not valid status code: 403, request id: d476095a7c9d14f6, host id: adX5uRGu4bldvFndAbvI=

s5cmd git:master Δ AWS_PROFILE=backblaze s5cmd --endpoint-url https://s3.us-west-000.backblazeb2.com ls
2021/06/22 15:50:03  s3://ig-testbucket-1
```

Could you check if it's the same thing for you as well?

**Comment by fishdust** [comment]
Hi @igundor,

Oof.. Embarrassing.. Thanks for spotting that.. 

I was only using the instructions noted on the [How to use s5cmd with B2](https://help.backblaze.com/hc/en-us/articles/360047171694-How-to-use-s5cmd-with-B2) page, which includes the following sample command with the other endpoint: 

`s5cmd -endpoint-url https://s3.us-west-002.backblazeb2.com ls`

According to the [B2 Cloud Storage Buckets page](https://secure.backblaze.com/b2_buckets.htm), the endpoint listed is `s3.us-west-000.backblazeb2.com` and does not indicate that this endpoint needs to be modified. When I change the endpoint from `https://s3.us-west-002.backblazeb2.com` to `https://s3.us-west-000.backblazeb2.com` the `s5cmd` command is successful.

**Comment by igungor** [comment]
Glad it worked for you too.

I opened a ticket to Backblaze. Support page doesn't allow me to share the link, so I took a screenshot.

I'm closing the issue. Thank you.

<img width="1021" alt="Screen Shot 2021-06-23 at 12 37 21" src="https://user-images.githubusercontent.com/8654/123074208-c63ea100-d41f-11eb-8310-2cad4888d002.png">
