### ISSUE TITLE
Unable to install s5cmd on ubuntu 18.04 with golang 1.15.   

### ISSUE THREAD

**Issue by dtsjbrown** [peak/s5cmd#271]
I installed go using the following command:
# sudo snap install go --classic

Output of "go version" is:
go version go1.15.6 linux/arm64

Running the command completes without any issues, but s5cmd doesn't actually install.   
sudo go get -u github.com/peakgames/s5cmd

Any ideas?

**Comment by igungor** [comment]
Could you try with `github.com/peak/s5cmd`?  How do you verify it's not installed?

**Comment by igungor** [comment]
I'm closing the issue. Please re-open if you think there's a problem.
