### ISSUE TITLE
s5cmd removes args in "run" mode

### ISSUE THREAD

**Issue by yosefy** [peak/s5cmd#273]
running like this:
cat commands.txt | /root/s5cmd run

cat commands.txt
cp -c=1 -p=1000000 /0000 s3://upload-test/
cp -c=1 -p=1000000 /0001 s3://upload-test/

when creating uploads, s5cmd removes "-c=1 -p=1000000" from commands
which are needed to work in gcp env

can you pls check?

thanks

**Comment by igungor** [comment]
Hi @yosefy 

Do you still see this problem? If so, could you share your s5cmd version please?

**Comment by igungor** [comment]
No response. Please re-open the ticket if you could provide more information so that we can reproduce the problem.
