### ISSUE TITLE
cp limited to 1000 files/objects ?

### ISSUE THREAD

**Issue by jansmets** [peak/s5cmd#276]
AWS_ACCESS_KEY_ID="X"  AWS_SECRET_ACCESS_KEY="Y"   s5cmd  --no-verify-ssl --endpoint-url http://ceph-rgw-endpoint  cp  's3://bucket/*'  /path/

This seems to only copy 1000 files and stops.
I'm using the latest official release.

**Comment by blacabexg** [comment]
Same here, my workaround what to use:

`find my-local-prefix/ -type f | awk '{ print "cp " $0 " s3://my-s3-bucket/my-s3-path/" }' > actions-to-perform.txt
s5cmd run actions-to-perform.txt`

Also, I was hitting to hard my NFS, had to add the `-numworkers 16` option

**Comment by jansmets** [comment]
I suspect it's due to a Ceph RGW issue. I'm on mimic.
