### ISSUE TITLE
Issue with read-only NFS share

### ISSUE THREAD

**Issue by eryabies** [peak/s5cmd#277]
For some reason s5cmd can't copy files from the read-only nfs share to s3 bucket

./s5cmd version
v1.2.1-3fc01af

./s5cmd --endpoint-url https://my-endpoint cp /read-only-nfs-share/testfile.txt s3://my-bucket/
ERROR "cp /read-only-nfs-share/testfile.txt  s3://my-bucket/testfile.txt": open /read-only-nfs-share/testfile.txt: read-only file system

**Comment by igungor** [comment]
This is fixed on master branch. It's not released yet. Could you try with master? We're planning to release it soon.
