### ISSUE TITLE
SignatureDoesNotMatch ERROR

### ISSUE THREAD

**Issue by theocampelo** [peak/s5cmd#278]
Hello

(Running on docker for Windows)

I've been trying to use s5cmd to list my buckets' contents (which are not on aws). I have specified the endpoint and I'm even able to list my buckets with **s5cmd ls**, but not what's inside them.

Upon trying something like:
`docker run --rm -v %UserProfile%\.aws:/root/.aws s5cmd --endpoint-url https://myendpoint ls s3://mybucket`

`ERROR "ls s3://mybucket": SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403, request id: tx160ab14735bb4576b9a7b-00605a2169, host id: tx160ab14735bb4576b9a7b-00605a2169`

Has anyone got any ideas?

Thanks in advance.
Regards, TC

**Comment by igungor** [comment]
Hi,

Which S3-compatible storage service you're working on? It looks like the service doesn't support ListObjectsV2 API request but I'm not totally sure.

**Comment by igungor** [comment]
No feedback. Please feel free to reopen the issue if you could provide more information.
