### ISSUE TITLE
How to utilize s5cmd performance enhancements in a fuse/mounted environment?

### ISSUE THREAD

**Issue by cayolblake** [peak/s5cmd#282]
Hello,

Apparently s5cmd provides great performance in comparison to any other s3 compatible client tested, however, I'm wondering how to benefit from it when using something like s3fuse?

Much appreciate the clarification.

**Comment by igungor** [comment]
Hi,

I'm not very familiar with s3fuse sorry. As far as I know, FUSE is an interface, so you're limited to the interface definition. s5cmd is not bound to any interface, so it can do more by parallelizing the jobs.

Please feel free to reopen the issue if you have any questions.
