### ISSUE TITLE
Is there any usable library to use in Python/PHP ?

### ISSUE THREAD

**Issue by cayolblake** [peak/s5cmd#283]
Hello,

Is it possible to utilize s5cmd in Python or PHP to communicate with s3 without relying on command line execution? 

I'm thinking something like a wrapper library or an API!

**Comment by igungor** [comment]
s5cmd is written in Go. There's no exported library currently. I don't think you can communicate with it other than executing it.

**Comment by jcfr** [comment]
For reference, the following issue is a proposal for streamlining the installation of `s5cmd` executable from Python:
* https://github.com/peak/s5cmd/issues/703
