### ISSUE TITLE
Is it possible to daemonize s5cmd ?

### ISSUE THREAD

**Issue by cayolblake** [peak/s5cmd#284]
Hello,

Is it possible to have `s5cmd` running as a daemon? Basically, accepting operations and processing them in an async fashion?

**Comment by igungor** [comment]
Hi,

What is your use case? How's this different than `s5cmd run`? It's good to know beforehand how this feature would be used.

**Comment by igungor** [comment]
No feedback. Please feel free to reopen the issue if you could provide more information.
