### ISSUE TITLE
Access to public buckets

### ISSUE THREAD

**Issue by LazydaveZ** [peak/s5cmd#285]
Hi currently I access a public bucket through asw cli with  --no-sign-request parameter.
I can not get s5cmd to replicate this behaviour it always fails with 403 permission denied

the bucket: 
s3://noaa-gfs-bdp-pds/

https://registry.opendata.aws/noaa-gfs-bdp-pds/

**Comment by fedorov** [comment]
On behalf of the [NCI Imaging Data Commons](https://portal.imaging.datacommons.cancer.gov/) developers and users - Thank you SO MUCH for adding this feature! All of our data is in public GCS buckets, and ability to access those without having to go through the torture of creating a service account and HMAC key is a life saver!
