### ISSUE TITLE
mv command does not respect part size

### ISSUE THREAD

**Issue by marcoabreu** [peak/s5cmd#289]
The MV command does not pass the part size down to the copy command. 

```s5cmd mv -p 1000 -c 32 ...```

**Comment by igungor** [comment]
Looks very similar to #273

Which s5cmd version are you using? Could you share the exact command please? If there're sensitive information, please redact.

**Comment by igungor** [comment]
No resopnse. Please re-open the issue if you have additional information you'd like to share.
