### ISSUE TITLE
SelectObjectContent support

### ISSUE THREAD

**Issue by skeggse** [peak/s5cmd#299]
I prototyped `SelectObjectContent` support (with wildcards) for `s5cmd`, and it works pretty well! I did make some assumptions, and it's not quite ready for primetime, and it'd take a bit of work to make it ready to go. I'm happy to open a PR if this is something you're open to supporting.

```sh
$ s5cmd select --query "SELECT * FROM S3Object s WHERE s.query_name LIKE '%.github.com.'" --compression-type gzip s3://example-bucket/AWSLogs/*
```

**Comment by igungor** [comment]
Hi @skeggse,

Looks very nice ✨ 

I'd personally be very happy to see this land on master branch. Also I'd gladly help if you have any questions.
