### ISSUE TITLE
Add "sync" command

### ISSUE THREAD

**Issue by Trane9991** [peak/s5cmd#3]
Would be nice to be able to have a smart `sync` command like [`s3cmd sync`](http://s3tools.org/s3cmd-sync) or [`aws s3 sync`](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html), which will upload the files that changed and remove the deleted ones.

**Comment by igungor** [comment]
Thanks for the feature request. It'll be a great addition to the current feature set.

Even though it's not the same as "sync", you can synchronize two directories (update if a file differs) with `s5cmd -u -s --parents s3://<bucket>/<folder> .`. Please keep in mind that it's not going to remove an existing object/file.

**Comment by kjaercasper** [comment]
A aws cli sync feature would be rally useful, so object are remove at bucket. Any news on a sync feature?

**Comment by missedone** [comment]
looking forward for a faster version of `s3 sync` as well

**Comment by missedone** [comment]
just got this project https://github.com/sethkor/s3kor supports fast sync

**Comment by favoyang** [comment]
> just got this project https://github.com/sethkor/s3kor supports fast sync

Here I quote from the s3kor repository page
> Sync only compares mod timestamps and sizes as the only true way to get a MD5 or some other checksum of an S3 object is to download it comletley first. An objects ETag is not the MD5 of the object.

Then it's very similar to `s5cmd cp -u -s`, except it did one more scan to remove non-existed keys. Sounds like an acceptable workaround, better than nothing.

**Comment by timureh** [comment]
Dear developers, do you plan to implement synchronization? For example like  https://github.com/sethkor/s3kor (without checking MD5). I cannot use s3kor because I have a non-AWS endpoint. s5cmd there is just an opportunity to use the --endpoint-url flag. that's what i need. orient us please

**Comment by ilkinulas** [comment]
Hi, `sync` is  on our roadmap, please follow this issue to be notified about any updates regarding s5cmd  sync implementation.

**Comment by vladimirsvicevicsrb** [comment]
Any update our new release version that includes `sync` operator? Thanks!

**Comment by sonmezonur** [comment]
s5cmd `v2.0.0-beta` is released. It includes `sync` command. Happy to receive your feedback and contributions!

**Comment by eminegit** [comment]
Hi, sync command works great with few files.  I am trying to sync 2 million files into s3 bucket which has more than 15 million files but I stops after 5 minutes with "killed" error message

**Comment by kristjanvalur** [comment]
Just had some issues replacing `aws s3 sync` with `s5cmd sync` and found that it requires trailing slashes to copy "folders", whereas `aws s3 sync` doesnt, treating slashes as any other prefix characters.
Might be good to explicitly mention that it isn't a drop-in replacement and that the source/destination specification is different.
