### ISSUE TITLE
brew fails when installing

### ISSUE THREAD

**Issue by caclifton** [peak/s5cmd#30]
Getting the following when trying to install s5cmd on mac os x 10.14.6, 
brew version : 
Homebrew 2.2.1
Homebrew/homebrew-core (git revision 7bbf; last commit 2019-12-12)

I first get this error : 
`brew install s5cmd
Error: Formulae found in multiple taps:
       * peakgames/s5cmd/s5cmd
       * peak/s5cmd/s5cmd

Please use the fully-qualified name (e.g. peakgames/s5cmd/s5cmd) to refer to the formula.`

If I then try 

`brew install peak/s5cmd/s5cmd
==> Installing s5cmd from peak/s5cmd
==> Downloading https://github.com/peak/s5cmd/archive/v0.6.0.tar.gz
Already downloaded: /Users/xcclifto/Library/Caches/Homebrew/downloads/764786c429df6e3f007dd53961a9e7778fb4d11fc19113ed0880794d4c8
eb669--s5cmd-0.6.0.tar.gz
==> go build -o /usr/local/Cellar/s5cmd/0.6.0/bin/s5cmd
Last 15 lines from /Users/xcclifto/Library/Logs/Homebrew/s5cmd/01.go:                                                                    /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peak/s5cmd/vendor/github.com/peakgames/s5cmd/complet
e (vendor tree)
        /usr/local/Cellar/go/1.13.4/libexec/src/github.com/peakgames/s5cmd/complete (from $GOROOT)
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peakgames/s5cmd/complete (from $GOPATH)
s5cmd.go:20:2: cannot find package "github.com/peakgames/s5cmd/core" in any of:
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peak/s5cmd/vendor/github.com/peakgames/s5cmd/core (v
endor tree)
        /usr/local/Cellar/go/1.13.4/libexec/src/github.com/peakgames/s5cmd/core (from $GOROOT)
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peakgames/s5cmd/core (from $GOPATH)
s5cmd.go:21:2: cannot find package "github.com/peakgames/s5cmd/stats" in any of:
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peak/s5cmd/vendor/github.com/peakgames/s5cmd/stats (vendor tree)                                                                                                                             /usr/local/Cellar/go/1.13.4/libexec/src/github.com/peakgames/s5cmd/stats (from $GOROOT)
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peakgames/s5cmd/stats (from $GOPATH)
s5cmd.go:22:2: cannot find package "github.com/peakgames/s5cmd/version" in any of:
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peak/s5cmd/vendor/github.com/peakgames/s5cmd/version
 (vendor tree)
        /usr/local/Cellar/go/1.13.4/libexec/src/github.com/peakgames/s5cmd/version (from $GOROOT)
        /private/tmp/s5cmd-20191212-45238-1woudal/s5cmd-0.6.0/src/github.com/peakgames/s5cmd/version (from $GOPATH)

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  peak/s5cmd

Traceback (most recent call last):
        26: from /usr/local/Homebrew/Library/Homebrew/build.rb:194:in `<main>'
        25: from /usr/local/Homebrew/Library/Homebrew/build.rb:113:in `install'
        24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
        23: from /usr/local/Homebrew/Library/Homebrew/build.rb:116:in `block in install'
        22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1128:in `brew'
        21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2036:in `stage'
        20: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
        19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:75:in `stage'
        18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:95:in `unpack'
        17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:171:in `mktemp'
        16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
        15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
        14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
        13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:172:in `block in mktemp'
        12: from /usr/local/Homebrew/Library/Homebrew/resource.rb:100:in `block in unpack'
        11: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2060:in `block in stage'
        10: from /usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
         9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2061:in `block (2 levels) in stage'
         8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1133:in `block in brew'
         7: from /usr/local/Homebrew/Library/Homebrew/build.rb:145:in `block (2 levels) in install'
         6: from /usr/local/Homebrew/Library/Taps/peak/homebrew-s5cmd/Formula/s5cmd.rb:20:in `install'
         5: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
         4: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
         3: from /usr/local/Homebrew/Library/Taps/peak/homebrew-s5cmd/Formula/s5cmd.rb:23:in `block in install'
         2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1864:in `system'
         1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1864:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1927:in `block in system': Failed executing: go build -o /usr/local/Cellar/s5cmd/
0.6.0/bin/s5cmd (BuildError)

9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'
        8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:141:in `rescue in <main>'
        7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
        6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:371:in `issues'
        5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:375:in `fetch_issues'
        4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:293:in `issues_for_formula'
        3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:279:in `search_issues'
        2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:388:in `search'
        1: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:213:in `open_api'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:259:in `raise_api_error': Validation Failed: [{"message"=>"The listed users
and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "reso
urce"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)`

**Comment by sonmezonur** [comment]
Could you please try:

```
brew untap peakgames/s5cmd
brew tap peak/s5cmd https://github.com/peak/s5cmd
brew install s5cmd
```
