### ISSUE TITLE
Hard crash on macos w/ v1.2.1-3fc01af

### ISSUE THREAD

**Issue by chisleu** [peak/s5cmd#302]
installed with homebrew. hardware is latest macbook. I do a "cat cmds | s5cmd run" and it will hard lock the system and give me the black screen of death. It's reproducable with some simple cp commands in the cmds file.

**Comment by igungor** [comment]
Could you share a reproducer? We haven't seen this problem before.

**Comment by igungor** [comment]
I'm closing the issue. If you could share a sample command file that I can reproduce the problem, please re-open and we'll take a look. Thanks.
