### ISSUE TITLE
cp: write access to source file required

### ISSUE THREAD

**Issue by throwException** [peak/s5cmd#306]
**Summary**
The cp operations needs write access to source files

**How to reproduce**
dd if=/dev/urandom of=testfile bs=1M count=4
chmod a-w testfile
s5cmd cp testfile s3://testbucket

**Expected result**
Upload works

**Actual result**
ERROR "cp testfile s3://testbucket": open testfile: permission denied

**Comment by igungor** [comment]
Thanks for the report. Could you try with the master branch? Its fixed with https://github.com/peak/s5cmd/issues/258 but not released yet.
