### ISSUE TITLE
Redesign region detection

### ISSUE THREAD

**Issue by ilkinulas** [peak/s5cmd#320]
We are using the following information to detect bucket region:
- AWS_REGION environtment variable
- `--source-region` and `--destination-region` options
- Region value returned from `head bucket` request

Document how and in which order  s5cmd uses these values.

**Comment by seruman** [comment]
Currently auto-region detection would always overrides the region in SDK config and causing us to ignore region given with `AWS_REGION/AWS_DEFAULT_REGION` environment variables or defined in given profile with `AWS_PROFILE` environment variable.

This causing issues with S3 compatible services returning empty response to `HeadBucket` request; which we used to detect bucket's region. #325, #354

#331 makes changes to address this issue.
