### ISSUE TITLE
s5cmd cp fails when glob evaluates to zero keys

### ISSUE THREAD

**Issue by satyanash** [peak/s5cmd#344]
on current `master`, if we run:
``` bash
s5cmd cp "s3://some-bucket/foo/bar/*" "./somewhere"
```

and there are no keys with prefix `s3://some-bucket/foo/bar/`, then the command returns exit code `1`.
This does not happen on `1.3.0`, so it looks like it is a newly introduced contract change.

While the new behavior is more consistent with how shell globs behave, I'm sure it is going to break some code out there.

**Comment by ocakhasan** [comment]
Hi @satyanash thanks for the information. We will add this feature in version 2.0.0.
