### ISSUE TITLE
Ignore Glacier warnings

### ISSUE THREAD

**Issue by sonmezonur** [peak/s5cmd#346]
After https://github.com/peak/s5cmd/commit/9defce6b615f10bd2be785ca42cf510ce3642bf8, commands have started to return exit status 1 if glacier warnings are encountered during execution. It is a breaking change for users who use version v1.3.0.  I think it would be useful to add a flag for turning on/off glacier warnings similar to ([--ignore-glacier-warnings](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/cp.html.))). As default, commands should exit with 0 for glacier warnings if we don't wanna break current API (v1.3.0).

**Comment by igungor** [comment]
Agreed.
