### ISSUE TITLE
s5cmd drops leading slashes in keys

### ISSUE THREAD

**Issue by gusostow** [peak/s5cmd#352]
Version: `v1.3.0-bb1775a`

Steps to reproduce:
```sh
$ touch file.txt
$ s5cmd cat s3://bucket/file.txt
ERROR "cat s3://bucket/file.txt": NoSuchKey: The specified key does not exist. status code: 404, request id: Z...BMQB76, host id: Yy5Y9JW0D9Nvx....NMdpe9/dbE=
$ s5cmd cp file.txt s3://bucket//file.txt
cp file.txt s3://bucket/file.txt
$ s5cmd cat s3://bucket/file.txt
$
```

You can compare this behavior to the aws CLI:
```sh
$ aws s3 cp file.txt s3://bucket//file.txt
upload: ./file.txt to s3://bucket//filet.txt
$ aws s3 cp s3://bucket//file.txt .
download: s3://bucket//file.txt to ./file.txt
```

Even more problematic, if there's an existing key with a leading slash, s5cmd won't be able to address it.

**Comment by gusostow** [comment]
Any thoughts on this?

**Comment by sonmezonur** [comment]
As you have pointed out, `s5cmd` does not handle leading slashes properly. Looks like there is an issue with [storage.URL](https://github.com/peak/s5cmd/blob/master/storage/url/url.go) package.
