### ISSUE TITLE
[Feature request] Support for "--profile" global cmdline option

### ISSUE THREAD

**Issue by yermulnik** [peak/s5cmd#353]
Could you please implement the `--profile` global cmdline option to allow switching between different AWS profiles and which should take precedence over `AWS_PROFILE` env var?
In other words, an option to mimic AWS CLI behavior: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

This would increase quality of user experience by having same option to switch between profiles in CLI.

Thanks in advance.

**Comment by AntonOks** [comment]
YES please... this would be a great enhancement and really make s5cmd a lot more usable...
