### ISSUE TITLE
log level and stats

### ISSUE THREAD

**Issue by bartek-siudeja** [peak/s5cmd#359]
Is it possible to prevent `s5cmd cp` from listing all copied files while still keeping `--stat` output? It seems that `--log error` is the only way to prevent s5cmd from listing files. Yet this also prevents `--stat` from working, as it is attached to info logging level. I have to copy thousands of files, and listing everything is too busy, so getting some kind of stats at the end would be nice. I don't think it would be unreasonable for `--stat` to force output independent of log level, since this is what user is asking for.

**Comment by igungor** [comment]
I think it's doable. `--stat` output should have no "level". If it is given, the output should be printed regardless of the log level.

If we do this, we must target for `version 2`. We can't break `version 1` compabibility.
