### ISSUE TITLE
part of a path removed by cp

### ISSUE THREAD

**Issue by bartek-siudeja** [peak/s5cmd#360]
I have run into the following strange behavior (on 1.4.0):
```
mkdir -p /mnt/data/folder/wildcard
touch /mnt/data/folder/wildcard/name
s5cmd cp "/mnt/data/folder/*/name" s3://bucket/folder/
cp /mnt/data/folder/wildcard/name s3://bucket/wildcard/name
```
For some reason target does not have `folder`.

**Comment by igungor** [comment]
Thanks for reporting this. It looks like a regression.

**Comment by gmarkey** [comment]
`sync` also exhibits the same behaviour (2.0.0 beta).
