### ISSUE TITLE
`go install github.com/peak/s5cmd@v1.4.0` is broken

### ISSUE THREAD

**Issue by ghost** [peak/s5cmd#368]
https://go.dev/blog/go116-module-changes#:~:text=In%20particular%2C%20replace%20and%20exclude%20directives%20are%20not%20allowed%2C
https://github.com/peak/s5cmd/blob/ce2537d38ba030c7f278ca9d81007b7f33fd0faf/go.mod#L24

**Comment by igungor** [comment]
```
$ go install github.com/peak/s5cmd@latest

go: downloading github.com/peak/s5cmd v1.4.0
go install: github.com/peak/s5cmd@latest (in github.com/peak/s5cmd@v1.4.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**Comment by aglossa** [comment]
Same pb when trying to use "go install". 
"go get" is deprecated by the Go team but "go get" (as specified in the current Readme of s5cmd) still works in this case. 
But in a future release of Go, it will be broken.
