### ISSUE TITLE
Bucket/key completion not supported?

### ISSUE THREAD

**Issue by Andreas5739738** [peak/s5cmd#372]
Hi,

I found some documentation (possibly for an old version?) which says that s5cmd supports bucket and key name completion:
https://reposhub.com/go/miscellaneous/peak-s5cmd.html

While I can use command completion just fine after running `--install-completion` (with s5cmd 1.1), it seems that bucket/key completion is not supported (at least I don't see any reaction when pressing tab while in an S3 URI). I also cannot find the implementation of such a feature in the master branch. Has the feature been removed or is there another branch I should be looking at?

Thanks!

**Comment by sonmezonur** [comment]
Hello @Andreas5739738 . We removed bucket/key completion after releasing `v1.0.0`. Documentation in [reposhub](https://reposhub.com/go/miscellaneous/peak-s5cmd.html) is not up to date. Please refer to [README](https://github.com/peak/s5cmd/blob/v1.4.0/README.md) for updated doc.

**Comment by sonmezonur** [comment]
Closing issue since we don't provide this feature anymore. Feel free to reopen it if you have more questions.

**Comment by Andreas5739738** [comment]
Hi Onur, thanks for the update. Any reason for removing this feature, or plans to re-add it? Thanks!

**Comment by sonmezonur** [comment]
As far as I remember, it was sending additional API requests to fetch buckets/keys and we thought it was not user-friendly (was working so slowly). We don't have plans for the near future but we prioritize issues according to feedbacks/reactions 🤷‍♂️
