### ISSUE TITLE
How is the integrity of uploaded files ensured?

### ISSUE THREAD

**Issue by linkvt** [peak/s5cmd#373]
Hi,

we are using s5cmd in a few projects and so far it works without issues while being really fast.

We were only wondering, how s5cmd ensures that uploaded files are stored in AWS as they are on the local file system.
Does s5cmd completely rely on e.g. TLS to ensure that network packets are not modified or is there some hashing of multipart parts that is used?
When checking the S3 API requests in AWS CloudTrail we couldn't see any info about an content hash.

Thanks, Vincent

**Comment by igungor** [comment]
Hey @linkvt 

Good question. We don't explicity check the integrity of the uploaded file as it is the same as on the local. As you point out, we only rely on the fact that requests are signed.

**Comment by sethgoldin** [comment]
Hi there, are there any plans to implement any kind of checksum verification, like xxHash? What good is speed if I can't be sure my files aren't corrupted on the destination?
