### ISSUE TITLE
sync command not found

### ISSUE THREAD

**Issue by brokosz** [peak/s5cmd#378]
Is sync currently disabled? I see the commit to main but not having any luck...

```
❯ s5cmd version
v1.4.0-d7a0dda
❯ s5cmd sync
ERROR "sync": command not found
```

**Comment by vikramarsid** [comment]
I see same issue using docker as well
```bash
docker run --network=host --rm peakcom/s5cmd sync --dry-run 's3://bucket-a/' 's3://bucket-b/'`
ERROR "sync": command not found
```

**Comment by kbarrette** [comment]
Looks like `sync` was added after d7a0dda8250ea2a189511d0e8e386f4fa43f9740 - I'm very much looking forward to the next release of s5cmd 😄

**Comment by igungor** [comment]
We plan to release the sync command with [s5cmd v2.0.0](https://github.com/peak/s5cmd/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3Av2.0.0).

**Comment by jamichalt** [comment]
Hi there! Any news about release v.2.0.0?

**Comment by vladimirsvicevicsrb** [comment]
Any update about release of `sync` operation?

**Comment by tooptoop4** [comment]
bump

**Comment by PDD777** [comment]
Release time frame from 1.4.0 -> 2.0.0 please?
Would really like to use "sync"
Unless alternative steps to reproduce could be supplied?

**Comment by alpereninci** [comment]
Any update about the version 2.0.0? If my download fails, I have to download all the files again. I cannot download 5TB data with this way.

**Comment by sonmezonur** [comment]
s5cmd `v2.0.0-beta` is out!  Looking forward to your feedback and contributions.
