### ISSUE TITLE
Provide updatable installation option for Ubuntu (eg. apt, snap, pip)

### ISSUE THREAD

**Issue by dreamflasher** [peak/s5cmd#380]
Please consider releasing this software to any package manager. This would allow keeping the software up-to-date without having a manual procedure just for this library.

**Comment by kedarv** [comment]
+1 would be great to distribute this as a deb, since it can be difficult to work with this sort of package distribution scheme if you don't have the ability to install go binaries / wget archives from github

**Comment by nattofriends** [comment]
As this repository uses goreleaser, would it be as simple as adding nfpm configuration to .goreleaser.yaml?

**Comment by seruman** [comment]
With https://github.com/peak/s5cmd/pull/437 we started releasing deb packages.
