### ISSUE TITLE
Peak throughput is good, but not sustained throughput

### ISSUE THREAD

**Issue by marsupialtail** [peak/s5cmd#402]
I benchmarked s5cmd vs aws s3 cli. I used a c5.2xlarge instance on AWS.

I tried to download a text file from S3, size ~ 50GB. 

With s5cmd I can get a peak of 4.3Gbps at the start of the download, which quickly drops to around 2Gbps. With aws s3 cli I hit 2Gbps at onset and just stay there. I am using -concurrency 16. 

Is this expected behavior? perhaps opening too many TCP connections means some will throttle others.

**Comment by igungor** [comment]
Hi,

Obviously it is not the expected outcome. This kind of benchmarks are very hard to comment on. You can set retry count to 0 if something's wrong going on under the hood, such as requests are waiting to be retried for some reason. You can change object concurrency and multipart concurrency parameters. There is no perfect configuration when it comes to saturating the network bandwidth. It's going to depend on your network setup, object sizes, etc.

Try tuning the parameters and see what's best for you. If you haven't seen it yet, this [post](https://joshua-robinson.medium.com/s5cmd-for-high-performance-object-storage-7071352cc09d) might help you.
