### ISSUE TITLE
Copy from Snowball Edge to local only copies 1000 files

### ISSUE THREAD

**Issue by dmbyte** [peak/s5cmd#405]
When performing a copy from an AWS Snowball Edge appliance to local, only 1000 files are copied.

**Comment by dmbyte** [comment]
Can you add a command line option to disable the use of the v2 list command (as I suspect that is what it is)

**Comment by dmbyte** [comment]
I've verified via my fork that forcing it back to the same command as the googleapi endpoint causes the copy and list to work.  I can read the code generally, but don't understand it enough to contribute the creation of a command line option to disable the flag.

**Comment by tianshiz** [comment]
does this happen when you copy from local to the snowball? Does it affect sync as well?

**Comment by sonmezonur** [comment]
Could you please try with `--use-v1-api` flag. If this solves your issue, let us know.

**Comment by dmbyte** [comment]
Given that @greenpau developed this based on my request and a quick build I had made to eliminate the ListObjectV2 path, I am pretty certain it will work, but will verify as soon as possible.

**Comment by igungor** [comment]
Should be fixed by https://github.com/peak/s5cmd/pull/407

Note that we've [changed](https://github.com/peak/s5cmd/pull/424) the flag to `--use-list-objects-v1`.

Please re-open the issue if your problem is not fixed by the above change.
