### ISSUE TITLE
Can't use s5cmd cp with file in hdfs?

### ISSUE THREAD

**Issue by tprebenda** [peak/s5cmd#413]
Is s5cmd not compatible with files in HDFS? I want to upload a file from hdfs to an s3 bucket.

Running the following command from linux:
`./packages/s5cmd --endpoint-url https://s3.us-east-1.amazonaws.com cp hdfs://path_to_parquet_file s3://my_bucket/path`

yields this error output:
`ERROR "cp hdfs://path_to_parquet_file s3://my_bucket/path": s3 url should start with "s3://"`

How can I resolve this issue? I can't access the files via relative path, I can

**Comment by igungor** [comment]
Hello @tprebenda 

`s5cmd` doesn't support hdfs. I'm closing the issue.
