### ISSUE TITLE
sync does not seem affected by part-size

### ISSUE THREAD

**Issue by tianshiz** [peak/s5cmd#416]
I have a single 200GB file that I'm trying to upload to my S3 bucket. I'm on a 10Gbps connection so I tried to increase part-size to maximize throughput.

However, sync doesn't seem to react to part-size in the same way as a normal cp. When I set a large enough part-size with cp, I can almost use the entire throughput. The same setting on sync nets me a disappointing 2Gbps. 

This is running on a windows 10 machine with latest from master

**Comment by sonmezonur** [comment]
`sync` in master branch does not use part-size and concurrency flags as you described. https://github.com/peak/s5cmd/pull/409 will fix this issue.

**Comment by sonmezonur** [comment]
PR is merged. Could you please test it? Feel free to reopen the issue if you still observe the same behavior.

**Comment by tianshiz** [comment]
thanks, will test it out. Btw, is there any difference between running sync and `cp -s -n -u`. Both achieve the same thing? Or does sync have some performance benefit?

**Comment by sonmezonur** [comment]
@tianshiz Copy and sync use the same interface so there won't be any performance improvement. It is depending on your use case, but you can use `cp -s -n -u` if it covers your needs. `sync` has more features and it is similar to aws cli sync.
