### ISSUE TITLE
Include Conda in install instructions

### ISSUE THREAD

**Issue by jakirkham** [peak/s5cmd#420]
Recently the [`s5cmd` package]( https://github.com/conda-forge/s5cmd-feedstock ) was added to [conda-forge]( https://conda-forge.org ). So using [Conda]( https://conda.io/en/latest/index.html ) should provide another way to install on macOS, Linux, and Windows. Maybe this is worth including in the install instructions here

**Comment by igungor** [comment]
Fixed with #468
