### ISSUE TITLE
`sync` fails with a large number of files to remove

### ISSUE THREAD

**Issue by kbarrette** [peak/s5cmd#435]
`sync` exits with status 1 and no error message when given a situation that results in a large number of deletions:

Run in an empty directory, which will cause around 500k deletions:
```
❯ s5cmd --log=debug --stat sync --delete . s3://my-bucket/lots-of-keys/

Operation	Total	Error	Success
sync		1	1	0

❯ echo $status
1
```

The same behavior also exists when running with the `--dry-run` flag.

Running the same command against an S3 path that results in 1 deletion works normally.

I realize this isn't a lot of information to work with - please let me know if I can provide more help somehow.

Thanks!

**Comment by sonmezonur** [comment]
Could you please try this setup in new release ([v2.0.0-beta.2](https://github.com/peak/s5cmd/releases/tag/v2.0.0-beta.2))? The issue should be resolved now. Feel free to reopen issue if you are still getting this behavior.
