### ISSUE TITLE
Add the --concurrency option to the documentation.

### ISSUE THREAD

**Issue by mikefarace** [peak/s5cmd#440]
The only place the --concurrency option for the cp command is shown, is in the release notes for the 1.0.0 version.  Please add it to the documentation page.  It is incredibly useful to increase the speed of copies for in some cases, limit bandwidth usage.

**Comment by boraberke** [comment]
@mikefarace What do you think about the following part? This part could be added to the documentation page.  Additionally an example will also be added to `s5cmd cp --help`.

#### Concurrency value tuning 

`s5cmd` supports changing the number of concurrent parts transferred between host and remote server in `cp` command with the `--concurrency` or `-c` flag.

    s5cmd cp --concurrency value directory/ s3://bucket

Will set the number of concurrent parts to `value`. This flag can be used to tune the throughput. It can be used to limit or increase the speed of the copy process. One use case could be to limit the bandwidth usage.

**Comment by boraberke** [comment]
Unintentionally closed the issue. Will be waiting for @mikefarace response.

**Comment by ilkinulas** [comment]
Hello @mikefarace Thanks for opening this issue.
A section about configuring concurrency is added to [README](https://github.com/peak/s5cmd#configuring-concurrency)
