### ISSUE TITLE
s5cmd --stat cp reports success with broken symlinks 

### ISSUE THREAD

**Issue by jkamalu** [peak/s5cmd#444]
If you try to copy a directory with symlinks from local storage to remote storage, the `s5cmd cp` command will automatically follow the links.

However, if the links are bad or broken, the command will fail and nothing will be uploaded, even if there are other data in the directory. However, if you use the `--stat` option when you invoke the command, it will report the executed copy as a success, which does not seem to be the correct behavior.

**Comment by jkamalu** [comment]
This issue is not about `cp` being broken, since we can just use `--no-follow-symlinks`. It is only about `--stat` reporting success when it should report failure.

**Comment by boraberke** [comment]
@jkamalu What are the steps to reproduce this failure of `--stat` flag?

**Comment by boraberke** [comment]
Hi @jkamalu,

I tried to reproduce this behavior with the following steps in s5cmd version v2.0.0, but I do not get any unexpected results from `--stat`:

```
 touch test1.txt test2.txt test3.txt
 ln -s test1.txt symlink
 rm test1.txt
 s5cmd --stat mb s3://bucket
 s5cmd --stat cp . s3://bucket/
```
gives as expected, an error:

```
ERROR "cp . s3://bucket/": given object not found
Operation	Total	Error	Success	
cp		1	1	0
```
If retried with `--no-follow-symlinks`, it executes it succesfully and results:
```
cp test2.txt s3://bucket/test2.txt
cp test3.txt s3://bucket/test3.txt

Operation	Total	Error	Success	
cp		1	0	1
```

**Comment by boraberke** [comment]
I'm closing this issue.  Please re-open if you can provide us a reproducer.
