### ISSUE TITLE
Tests failed on AlpineLinux 32bit architecture

### ISSUE THREAD

**Issue by FollieHiyuki** [peak/s5cmd#446]
Hi! I'm trying to package `s5cmd` for AlpineLinux. The attempt can be seen [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/35426).

Some problems I'm facing:
- `e2e` tests are failing on 32bit architecture builds. [Sample logs on x86](https://gitlab.alpinelinux.org/FollieHiyuki/aports/-/jobs/746921/raw)
- `-race` flag is specified in [e2e/util_test.go line 216](https://github.com/peak/s5cmd/blob/7200415a06500f88cad95ed48e7aa33bc023a915/e2e/util_test.go#L216) which is not compatible with `-buildmode=pie`. Is there a way to configure it during the build process?

I'd love to get some advice. And thanks for `s5cmd`!

**Comment by Kucukaslan** [comment]
Hi again, 
You can disable "race" flag[^1] by using `make test_without_race` instead of `make test` or `go test ./...`

[^1]: that is used to build test binary.

**Comment by FollieHiyuki** [comment]
Thanks a bunch. Will try to build again when the new release is out.
