### ISSUE TITLE
s5cmd doesn't support aws signature version 4

### ISSUE THREAD

**Issue by adamcohenhillel** [peak/s5cmd#448]
Can not find a way to run s5cmd with sigv4 option of aws, which is enforced by many regions by now 

https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html

go SDK  https://docs.aws.amazon.com/sdk-for-go/api/aws/signer/v4/

**Comment by adamcohenhillel** [comment]
I see there is this file: https://github.com/peak/s5cmd/blob/master/vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
but is it used by default? if not, should I pass any flag to trigger it?

**Comment by ilkinulas** [comment]
`s5cmd --log trace` will write out the HTTP requests sent to s3 endpoint.
You can see the signing details in `Authorization` header.

By looking at the trace logs, I can say that  by default signature version 4 is used.

```
Authorization: AWS4-HMAC-SHA256 ......
```
