### ISSUE TITLE
Understanding numworkers

### ISSUE THREAD

**Issue by gusostow** [peak/s5cmd#464]
How is this parameter different than --concurrency? How should these two be tuned together? I'd appreciate some more info in the docs. Thanks!

**Comment by ilkinulas** [comment]
Hello @gusostow 
Thank you for pointing this out, I've just added a section for numworkers and concurrency options in README.

**Comment by gusostow** [comment]
Is there a threshold for multi-part uploads?

**Comment by ilkinulas** [comment]
> Is there a threshold for multi-part uploads?

Is [this](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html)  what you are asking for?
