### ISSUE TITLE
Broken AWS_REGION environment variable

### ISSUE THREAD

**Issue by sonmezonur** [peak/s5cmd#484]
This command fails in version `v2.0.0-35bb2fa`

```
 AWS_REGION=us-east-2 s5cmd ls s3://backup-bucket/
 ERROR "ls s3://backup-bucket/": BucketRegionError: incorrect region, the bucket is not in 'us-east-2' region at endpoint '' status code: 301, request id: , host id:

```

I would like to use `AWS_REGION` env but getting an error that indicates the given endpoint is an empty string ("").

Tried same command with `v1.4.0` and it works as expected

**Comment by seruman** [comment]
Seems broken with https://github.com/peak/s5cmd/commit/6fac3f106c97f7ffe5d33c44800e486af5450da3
