### ISSUE TITLE
use S5CMD download files only get 1000 files?

### ISSUE THREAD

**Issue by Master-lb** [peak/s5cmd#487]
This is my run code:
s5cmd --endpoint-url http://XXXXX sync s3://BUCKET_NAME/*  /dest_dir
or
s5cmd --endpoint-url http://XXXXX cp s3://BUCKET_NAME/*  /dest_dir

then I check /dest_dir only 1000 files。

**Comment by boraberke** [comment]
Hi @Master-lb,

It might be related to the endpoint you are using. Which S3 compatible storage service do you use? Also, could you please share your `s5cmd` version?

**Comment by Master-lb** [comment]
Thanks for you reply, my s5cmd  version is v2.0.0-35bb2fa  ，I don't know what effect it has. Can you help me?

> 你好@Master-lb,
> 
> 它可能与您正在使用的端点有关。您使用哪种 S3 兼容存储服务？另外，可以分享一下你的`s5cmd`版本吗？

**Comment by boraberke** [comment]
And also, which S3 compatible storage service do you use?

**Comment by Master-lb** [comment]
> 
thanks boy！
I set --use-list-objects-v1 is working right。 I think，It has something to do with it

**Comment by boraberke** [comment]
I'm closing this issue as `--use-list-objects-v1` solved the problem in your case. Feel free to reopen the issue if you are still getting this behavior.
