### ISSUE TITLE
Caching s3 bucket file listing and file properties

### ISSUE THREAD

**Issue by autronix** [peak/s5cmd#497]
Hello,

I have a use case with around 30Tb of data across ~145M files.

I'm currently attempting a `sync` command with S3 on a portion of that (around 2Tb in size). 
When the sync process starts, it takes around 6-8h before s5cmd starts downloading the content, I'm guessing this is due to the listing process associated with getting the file names, file sizes and modified dates.

Doing a `du` on the entire set takes about 10-15h:
```bash
35.9T bytes in 145295227 objects: s3://my_very_large_bucket/*
```

I think having a cache file or having the option of caching the list of files+properties (file name, size, date, etc) to sync (ls, du) would prevent the sizable overhead associated with reinitiating a sync process in case of failure.

The idea here is to create a reference file listing cache file with all the necessary information to be able to run this against the s5cmd commands without having to re-query s3 every time.

**Comment by ilkinulas** [comment]
Hello, thank you for your patience  :)

S5cmd is a general-purpose tool. While your proposed solution addresses your specific issue, saving the state of the bucket at an arbitrary time and later using that state for sync in a shared bucket could lead to inconsistencies with the current state of the bucket. 

As you noted, these checks are in place to ensure that the original bucket/prefix remains the source of truth for sync operations. I am closing this issue for now. Please feel free to reopen it if you have any other suggestions.
