### ISSUE TITLE
Add console progress bar for multipart upload/download

### ISSUE THREAD

**Issue by sonmezonur** [peak/s5cmd#51]
Currently, s5cmd does not show the progress of multipart operations. It would be nice to add an option to display the progress for large files.

**Comment by geosigno** [comment]
Any update or workaround to get a progress event?

**Comment by ochaton** [comment]
It would be nice if s5cmd would show progress bar for `cp` command

**Comment by leng-yue** [comment]
Any update?

**Comment by sorenwacker** [comment]
So far this feature is not available.

**Comment by mwtoews** [comment]
It would be excellent if this option were also available for `sync` too.
