### ISSUE TITLE
Using virtual hosted style in Alibaba OSS

### ISSUE THREAD

**Issue by sumodirjo** [peak/s5cmd#518]
Hello,

I got the following error when trying to list OSS bucket contents. e.g " s5cmd ls s3://<oss-bucket-name>/

```
ERROR "ls s3://<oss-bucket-name/": SecondLevelDomainForbidden: Please use virtual hosted style to access. status code: 403, request id: <request-id>, host id:
```

From Readme I learned:

> s5cmd will use virtual-host style bucket resolving for S3, S3 transfer acceleration and GCS. If a custom endpoint is provided, it'll fallback to path-style.

How can I set s5cmd to use virtual-host style when working with Alibaba OSS? Thank you.

**Comment by igungor** [comment]
Hi,

Currently, there's no way to configure other than changing the source code. Please feel free to open a PR.

**Comment by LinPr** [comment]
Alibaba OSS  forbid the path style host when uploading object to bucket, but you can request for technical support of Alibaba OSS， and  they will help add your bucket to a white list， then you can upload or download files with path style host.

And i have already verified this，it reall works !! 

![Image](https://github.com/user-attachments/assets/522bbb0e-fae0-44b1-9cd5-7af70c8d4034)
