### ISSUE TITLE
Read local object from STDIN 

### ISSUE THREAD

**Issue by snebel29** [peak/s5cmd#522]
Hi,
This topic has been discussed before, at least in https://github.com/peak/s5cmd/issues/182.

I am just weighting (once more) the apetite for s5cm to provide this feature, to get a contribution and if the answer is positive, what the ideal approach could be.

Cheers.

**Comment by igungor** [comment]
Hey,

There's an open PR https://github.com/peak/s5cmd/pull/587 to resolve this issue.
