### ISSUE TITLE
Is mounting of buckets possible?

### ISSUE THREAD

**Issue by venomone** [peak/s5cmd#523]
Hello,

I'm in search for a tool that can do high parallel multipart uploads/downloads and can be mounted as file system under Linux. Does s5cmd fulfill these requirements, can I mount an S3 bucket ? If not, is it on the roadmap for the feature?
One use case for this is streaming HLS/DASH media to many clients, using a web server in front of the mount point to send the files to the client.

**Comment by ilkinulas** [comment]
Hi
`s5cmd` can do high parallel multipart uploads/downloads but can not mount s3 as a file system. You should check tools like [s3fs](https://github.com/s3fs-fuse/s3fs-fuse) for mounting s3 buckets.
