### ISSUE TITLE
Preserve the full path with cp

### ISSUE THREAD

**Issue by praveenraj2018** [peak/s5cmd#524]
Hi

Wondering if _cp_ can preserve the full path when copying data from local to s3?
I have recently come across a use case as below and s5cmd does it as flatten

```
s5cmd cp -n -s -u human/set1/hg_1.fastq.gz s3://genome/
s5cmd cp -n -s -u human/set2/hg_1.fastq.gz s3://genome/
s5cmd cp -n -s -u human/set3/hg_1.fastq.gz s3://genome/
s5cmd cp -n -s -u human/set4/hg_1.fastq.gz s3://genome/
```
at the end, I see only one hg_1.fastq.gz in s3://genome/

Even the following does not work for me either:

```
s5cmd cp -n -s -u human/*/hg_1.fastq.gz s3://genome/
s5cmd cp -n -s -u human/*/*.fastq.gz s3://genome/
ERROR "cp human/set1/hg_1.fastq.gz human/set2/hg_1.fastq.gz human/set3/hg_1.fastq.gz human/set4/hg_1.fastq.gz s3://genome/": expected source and destination arguments
```

Can we have _--parents_ by default internally in _cp_ in this case as well? I remember it has been done for s3 > local, but not local > s3. 

Correct me if I am wrong. Otherwise, how do we do the above with existing commands/options?

**Comment by Kucukaslan** [comment]
> s5cmd cp -n -s -u human/*/hg_1.fastq.gz s3://genome/
> s5cmd cp -n -s -u human/*/*.fastq.gz s3://genome/
> ERROR "cp human/set1/hg_1.fastq.gz human/set2/hg_1.fastq.gz human/set3/hg_1.fastq.gz human/set4/hg_1.fastq.gz s3://genome/": expected source and destination arguments

I guess the `*` is expanded by the shell.

Can you try with source arguments quoted? As follows:
``` 
s5cmd cp -n -s -u "human/*/hg_1.fastq.gz" s3://genome/
```

**Comment by Kucukaslan** [comment]
> It is failing even with quotes,

It seems you've forgotten to create the bucket.

```
$ s5cmd ls s3://genomic-1
ERROR "ls s3://genomic-1": no object found
$ s5cmd cp -n -s -u "human/*/hg_1.fastq.gz" s3://genomic-1/
cp human/set2/hg_1.fastq.gz s3://genomic-1/set2/hg_1.fastq.gz
cp human/set3/hg_1.fastq.gz s3://genomic-1/set3/hg_1.fastq.gz
cp human/set1/hg_1.fastq.gz s3://genomic-1/set1/hg_1.fastq.gz
cp human/set4/hg_1.fastq.gz s3://genomic-1/set4/hg_1.fastq.gz
$ s5cmd ls s3://genomic-1
                                  DIR set1/
                                  DIR set2/
                                  DIR set3/
                                  DIR set4/
$ s5cmd ls "s3://genomic-1/*"
2022/10/31 21:38:57                 0 set1/hg_1.fastq.gz
2022/10/31 21:38:57                 0 set2/hg_1.fastq.gz
2022/10/31 21:38:57                 0 set3/hg_1.fastq.gz
2022/10/31 21:38:57                 0 set4/hg_1.fastq.gz
```

> can the `CP` create the parent directories

with `s5cmd cp -n -s -u human/set/hg1.txt s3://genomic-1/` it won't but alternatively you can execute `s5cmd cp -n -s -u human/set/hg1.txt s3://genomic-1/human/set/` or `s5cmd cp -n -s -u human/set/hg1.txt s3://genomic-1/human/set/hg1.txt`  to   put file to `s3://genomic-1/human/set/hg1.txt`

**Comment by praveenraj2018** [comment]
The following worked. Great!

`s5cmd cp -n -s -u human/set/hg1.txt s3://genomic-1/human/set/hg1.txt`

Thanks!

**Comment by Kucukaslan** [comment]
> Thanks!

You're welcome!
