### ISSUE TITLE
Can this solution be used in a mobile application to speed uploads to s3? 

### ISSUE THREAD

**Issue by eyekay234** [peak/s5cmd#533]
I have a mobile application where users upload videos and images that are processed on ec2 instance on aws and then stored on selected s3 buckets.

I want to know if this can be used for making user uploads to s3 buckets faster as presently there is a huge latency being experienced on the app when users try to upload videos they create using the mobile application

Any help @Kucukaslan @ilkinulas

**Comment by ilkinulas** [comment]
Hello, s5cmd is not designed to run on mobile devices. I can not be used as an iOS or Android sdk for uploading files to s3. You should use the appropriate mobile client sdks  to upload your files to s3. Multipart uploads may speed up the uploads from mobile clients to s3.
