### ISSUE TITLE
Support `--raw` flag with `cat`

### ISSUE THREAD

**Issue by PApostol** [peak/s5cmd#539]
This PR #315 has added `--raw` as a flag for `cp` and `rm` operations. It would be nice to have it for `cat` as well. Currently, we have to use AWS CLI to cat a file on S3 with "*" in the object key; keen on being able to use s5cmd for everything :)

**Comment by Kucukaslan** [comment]
If merged, #475 will add `--raw` flag to `cat` and `select` subcommands. 
Though, it might have been better to make that change in a seperate PR.
