### ISSUE TITLE
Read the minio client -- `mc` -- confguration file ~/.mc/config.json

### ISSUE THREAD

**Issue by EvanCarroll** [peak/s5cmd#544]
According to the docs,

> s5cmd reads `.aws/credentials` to access Google Cloud Storage. Populate the `aws_access_key_id` and `aws_secret_access_key` fields in `.aws/credentials` with an HMAC key created using this [procedure](https://cloud.google.com/storage/docs/authentication/managing-hmackeys#create).

I'm not sure about aws, but that sounds like minio's `~/.mc/config.json`, which by default looks something like this. This is how you configure the default [minio `mc` client.](https://min.io/docs/minio/linux/reference/minio-mc.html)

```json
{
	"version": "10",
	"aliases": {
		"gcs": {
			"url": "https://storage.googleapis.com",
			"accessKey": "YOUR-ACCESS-KEY-HERE",
			"secretKey": "YOUR-SECRET-KEY-HERE",
			"api": "S3v2",
			"path": "dns"
		},
		"local": {
			"url": "http://localhost:9000",
			"accessKey": "",
			"secretKey": "",
			"api": "S3v4",
			"path": "auto"
		},
		"s3": {
			"url": "https://s3.amazonaws.com",
			"accessKey": "YOUR-ACCESS-KEY-HERE",
			"secretKey": "YOUR-SECRET-KEY-HERE",
			"api": "S3v4",
			"path": "dns"
		}
	}
}
```

It would be nice if s5cmd could configure itself with that.

**Comment by igungor** [comment]
Hey,

Sorry, we don't have any plans to support mc config file. s5cmd tries to be as close as possible to the official AWS Go SDK.
