### ISSUE TITLE
Moving from S3 to S3, it keeps pausing..

### ISSUE THREAD

**Issue by bobmoff** [peak/s5cmd#550]
It goes fast for a few seconds.. then stalls for a very long time.. like 30 sec.. then goes on for a while.. and stops again.

When using aws cli tools, it goes in a steady rate without interruptions.

**Comment by igungor** [comment]
Could you run it again with `s5cmd --log trace` flag? Printed request/response logs might help debug the problem.

**Comment by igungor** [comment]
I'm closing the issue. If you have more details, please feel free to reopen the case.
