### ISSUE TITLE
Importing s5cmd v2 as dependency

### ISSUE THREAD

**Issue by MirkoGibin** [peak/s5cmd#562]
Hi everyone, I tried to import s5cmd as a dependency in one of my projects with `go get github.com/peak/s5cmd@v2.0.0` but it fails with `go: github.com/peak/s5cmd@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/peak/s5cmd/v2")`.

I found this PR: [Bump go module version to v2](https://github.com/peak/s5cmd/pull/556).

Is there any plan to merge that PR or to make s5cmd v2 module available?

**Comment by igungor** [comment]
We plan to migrate to `v2` just because `go install` doesn't work out of the box. Please keep in mind that `s5cmd` is not a Go package, and neither do we have a plan to release it as a package.
