### ISSUE TITLE
Workers gets stuck after processing a single command when processing a list of commands

### ISSUE THREAD

**Issue by Boreas7** [peak/s5cmd#58]
I have a file "commands.txt" with a list of commands like this:

> cp -n s3://bucket1/file1 s3://bucket2/file1
> cp -n s3://bucket1/file2 s3://bucket2/file2
> cp -n s3://bucket1/file3 s3://bucket2/file3
> ...

When I call s5cmd like

> s5cmd -numworkers 2 -f commands.txt

I see output like

> 2020/02/17 23:24:47 # Using 2 workers
2020/02/17 23:24:47 +OK "cp s3://bucket1/file1 s3://bucket2/file1"
2020/02/17 23:24:47 +OK "cp s3://bucket1/file2 s3://bucket2/file2"

and then it gets stuck, until I hit Ctrl-C and see the following output

> 2020/02/17 23:23:31 # Got signal, cleaning up...
2020/02/17 23:23:31 # Exiting with code 0
2020/02/17 23:23:31 # Stats: S3               3    0 ops/sec
2020/02/17 23:23:31 # Stats: Total            3    0 ops/sec 1m19.084946532s

The first 2 files are actually copied correctly, the rest of the commands from the file is not executed. Same with taking the commands from the standard input.

I just installed the latest version of s5cmd - v0.7.0.

Deleting all the objects from the second bucket works fine with a command like:

> s5cmd rm s3://bucket2/*

Any suggestions for workaround?

Thanks.

**Comment by Boreas7** [comment]
Hmm, I see the same behavior with a batch command like 

> s5cmd --numworkers 2 -gops "cp --parents s3://bucket1/* s3://bucket2/"

The stack trace:

> goroutine 20 [running]:
runtime/pprof.writeGoroutineStacks(0xab9980, 0xc00056fd80, 0x30, 0xc000167500)
	/usr/lib/golang/src/runtime/pprof/pprof.go:679 +0x9d
runtime/pprof.writeGoroutine(0xab9980, 0xc00056fd80, 0x2, 0x8ba2252f, 0x531a3268d8a2d39)
	/usr/lib/golang/src/runtime/pprof/pprof.go:668 +0x44
runtime/pprof.(*Profile).WriteTo(0xdeec80, 0xab9980, 0xc00056fd80, 0x2, 0x8f6500, 0xc0006a7d40)
	/usr/lib/golang/src/runtime/pprof/pprof.go:329 +0x3da
github.com/peak/s5cmd/vendor/github.com/google/gops/agent.handle(0xab9980, 0xc00056fd80, 0xc0000954a8, 0x1, 0x1, 0x0, 0x0)
	/home/user/go/src/github.com/peak/s5cmd/vendor/github.com/google/gops/agent/agent.go:171 +0x177
github.com/peak/s5cmd/vendor/github.com/google/gops/agent.listen()
	/home/user/go/src/github.com/peak/s5cmd/vendor/github.com/google/gops/agent/agent.go:119 +0x275
created by github.com/peak/s5cmd/vendor/github.com/google/gops/agent.Listen
	/home/user/go/src/github.com/peak/s5cmd/vendor/github.com/google/gops/agent/agent.go:100 +0x443

> goroutine 1 [select, 1 minutes]:
github.com/peak/s5cmd/core.(*WorkerPool).pumpJobQueues(0xc0000a87d0)
	/home/user/go/src/github.com/peak/s5cmd/core/worker.go:178 +0x23e
github.com/peak/s5cmd/core.(*WorkerPool).RunCmd(0xc0000a87d0, 0x7ffcc825748f, 0x46)
	/home/user/go/src/github.com/peak/s5cmd/core/worker.go:194 +0xb9
main.main()
	/home/user/go/src/github.com/peak/s5cmd/main.go:189 +0xa2b

> goroutine 19 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

> goroutine 21 [chan receive, 1 minutes]:
main.main.func3(0xc00008d8c0)
	/home/user/go/src/github.com/peak/s5cmd/main.go:168 +0xbd
created by main.main
	/home/user/go/src/github.com/peak/s5cmd/main.go:165 +0x902

> goroutine 23 [select, 1 minutes]:
github.com/peak/s5cmd/core.wildOperation(0xc0000a69c0, 0xc00007b200, 0xc000247ca0, 0xc000095010, 0xa)
	/home/user/go/src/github.com/peak/s5cmd/core/job.go:254 +0x27e
github.com/peak/s5cmd/core.S3BatchCopy(0xc00017abd0, 0xc00007b200, 0x6, 0xc00017a708, 0x40e301)
	/home/user/go/src/github.com/peak/s5cmd/core/op_s3.go:266 +0x119
github.com/peak/s5cmd/core.(*Job).run(0xc00017abd0, 0xc00007b200, 0xc0000a8968, 0xc000054f60)
	/home/user/go/src/github.com/peak/s5cmd/core/job.go:197 +0xaa
github.com/peak/s5cmd/core.(*Job).Run(0xc00017abd0, 0xac4780, 0xc00017ce70, 0xc0000a8780, 0xc0000a2b80, 0xc0000a87f0, 0xc0000a8818, 0xc00008d8d0, 0x0)
	/home/user/go/src/github.com/peak/s5cmd/core/job.go:203 +0x84
github.com/peak/s5cmd/core.(*WorkerPool).runWorker(0xc0000a87d0, 0xc0000a2b80, 0xc0000a8818, 0x1)
	/home/user/go/src/github.com/peak/s5cmd/core/worker.go:130 +0x3e7
created by github.com/peak/s5cmd/core.NewWorkerPool
	/home/user/go/src/github.com/peak/s5cmd/core/worker.go:83 +0x1ef

> goroutine 25 [chan send, 1 minutes]:
github.com/peak/s5cmd/storage.(*S3).List.func1.1(0xc0000f6e80, 0xc00007b300, 0xc00017d590)
	/home/user/go/src/github.com/peak/s5cmd/storage/s3.go:141 +0x4bc
github.com/peak/s5cmd/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc0000a4160, 0xac4780, 0xc00017ce70, 0xc0000a8a50, 0xc00017d590, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/peak/s5cmd/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4652 +0x111
github.com/peak/s5cmd/storage.(*S3).List.func1(0xc00007c780, 0xc00017aea0, 0xac4780, 0xc00017ce70, 0xc0000a8a50, 0xc0000a69c0, 0x1)
	/home/user/go/src/github.com/peak/s5cmd/storage/s3.go:120 +0x13a
created by github.com/peak/s5cmd/storage.(*S3).List
	/home/user/go/src/github.com/peak/s5cmd/storage/s3.go:116 +0x16e

**Comment by sonmezonur** [comment]
@Boreas7  Currently, there is a bug on batch operations. When the number of jobs is bigger than the worker count, batch operations get stuck. We are going to resolve this in the future releases. Thanks for the feedback.

**Comment by Boreas7** [comment]
Onur, thanks a lot for the prompt response! I was just about to comment that I discovered the same :-)

Are there any earlier versions without the bug?

I'll try a workaround of using the big number of worker threads. The performance will not be that great but still may be better than alternatives.

**Comment by Boreas7** [comment]
Thanks to the Go lightweight threading I was able to test s5cmd with up to 500,000 workers. 1 mln would probably work as well but it required more than 8 Gb of memory I had on my machine.

**Comment by Boreas7** [comment]
It would be nice to update the documentation about this pretty serious issue, so others would not waste time on researching it.

Feel free to close as a dup if you already have a ticket for the problem. Otherwise I think it is a good idea to keep it open until it is fixed.

**Comment by igungor** [comment]
Hey @Boreas7, thanks for the detailed report. It's been helpful. We're working on a fix and will let you know once a PR is landed. Let's keep the issue open until then.

**Comment by sonmezonur** [comment]
Hi @Boreas7 . We fixed the bug and released [v1.0.0](https://github.com/peak/s5cmd/releases/tag/v1.0.0). 

If you are still encountering this problem, feel free to reopen the issue and ping us :)
