### ISSUE TITLE
How to measure performance ?

### ISSUE THREAD

**Issue by Tulsishah** [peak/s5cmd#580]
Hi,
I want to measure read, write, list, create ,delete workflows performance. Is there any tool, script or any way to measure the same?

Thanks,
Tulsi Shah

**Comment by igungor** [comment]
Hi,

Please take a look at [benchmark](https://github.com/peak/s5cmd/tree/master/benchmark) directory. `bench.py` script compares 2 different builds of `s5cmd`, but you may modify it to suit your use case.
