### ISSUE TITLE
Does s5cmd support Signature V2 ?

### ISSUE THREAD

**Issue by nguyenvandiepbvh** [peak/s5cmd#608]
s5cmd --use-list-objects-v1 ls
ERROR "ls": SignatureDoesNotMatch:  status code: 403

We have a Ceph Cluster ( pacific version ), its only run Signature V2.

We used s3cmd before and s3cmd support Signature V2. Does s5cmd support it too ?

If yes, pls guide us how to config it

Thank you

**Comment by nguyenvandiepbvh** [comment]
found answer 

https://github.com/peak/s5cmd/issues/236

**Comment by robbat2** [comment]
@nguyenvandiepbvh 
:wave: Hi from the Ceph development side. 

I'm wondering why you said `We have a Ceph Cluster ( pacific version ), its only run Signature V2`
Ceph has supported V4 signatures since before 2018 (but the Jewel release in 2018 had some significant bugfixes).
