### ISSUE TITLE
Add --skip-existing

### ISSUE THREAD

**Issue by markkdev** [peak/s5cmd#648]
Hi,

I was wondering if there were any plans in the future to include a `--skip-existing` flag similar to the [one provided by s3cmd](https://s3tools.org/s3cmd-sync).

P.S. wanted to thank you for this wonderful tool, our asset upload time dropped from 2-5mins to 8-12s after migrating from s3cmd!

**Comment by k0ste** [comment]
@markkdev `--if-size-differ` and `--if-source-newer` is not the same?

**Comment by igungor** [comment]
@markkdev we have such a feature under the flag `--no-clobber`. You may use it like below:

```
$ s5cmd --log=debug cp file1 s3://bucket/ibrahim/             
cp file1 s3://bucket/ibrahim/file1  # initial upload

$ s5cmd --log=debug cp file1 s3://bucket/ibrahim/
cp file1 s3://bucket/ibrahim/file1  # override destination object

$ s5cmd --log=debug cp --no-clobber file1 s3://bucket/ibrahim/
DEBUG "cp file1 s3://bucket/ibrahim/file1": object already exists
```
