### ISSUE TITLE
Sync interregional S3 to S3 

### ISSUE THREAD

**Issue by LeafmanZ** [peak/s5cmd#654]
I have been playing around with s5cmd using the cp command to move data from one AWS-S3 bucket to another AWS-S3 bucket in another region. The following worked perfectly.

./s5cmd cp --source-region my-source-region --destination-region my-destination-region 's3://mysourcebucket/*' s3://mydestinationbucket/

However, I want to do this with the sync command, but when I ran the following command I received the following error.
./s5cmd sync --source-region my-source-region --destination-region my-destination-region 's3://mysourcebucket/*' s3://mydestinationbucket/

ERROR "sync s3://mysourcebucket/* s3://mydestinationbucket/": RequestError: send request failed caused by: Get "https://testregion-s3.s3.none.amazonaws.com/?list-type=2&prefix=test0%2F0%2F": dial tcp: lookup testregion-s3.s3.none.amazonaws.com on 10.129.0.2:59: no such host 

How can I use the sync command to sync data between interregional AWS S3 buckets?

**Comment by jf20541** [comment]
pip install region-translator - for when your buckets have an identity crisis between regions! 🌏↔️🌍😂
