### ISSUE TITLE
Update version tags for `go install`

### ISSUE THREAD

**Issue by dprestegard** [peak/s5cmd#662]
``` bash
go list -m -versions github.com/peak/s5cmd

github.com/peak/s5cmd v0.5.0 v0.5.1 v0.5.2 v0.5.3 v0.5.4 v0.5.5 v0.5.6 v0.5.7 v0.5.8 v0.6.0 v0.6.1 v0.6.2 v0.7.0 v0.7.1 v0.7.2 v1.0.0 v1.1.0 v1.2.0 v1.2.1 v1.3.0 v1.4.0-rc.1 v1.4.0
```
Sadly although we're on v2.2.2, the latest tag here is v1.4.0

I'd like to get a recent version and would rather be able to pin a specific version in my Dockerfile instead of using `master`

**Comment by Kucukaslan** [comment]
I guess the go list filters with respect to versions too.

```sh
go list -m -versions github.com/peak/s5cmd/v2
```
prints
>github.com/peak/s5cmd/v2 v2.0.0-beta v2.0.0-beta.2 v2.0.0 v2.1.0-beta.1 v2.1.0 v2.2.0 v2.2.1 v2.2.2

**Comment by igungor** [comment]
I'm closing this issue as @Kucukaslan's comment should address your requirement. Thank you.
