### ISSUE TITLE
How to use s5cmd with a proxy?

### ISSUE THREAD

**Issue by BG4WCE** [peak/s5cmd#665]
Is it possible to use s5cmd with a proxy?

**Comment by seruman** [comment]
Hi @BG4WCE,

You can use `HTTP_PROXY` and `HTTPS_PROXY` environment variables to point to your proxy.  As `s5cmd` uses official AWS Go SDK it defaults to use SSL. You may need to set up your host to accept your proxy's CA certificate or disable SSL verification with `--no-verify-ssl` flag, e.g;
```
HTTP_PROXY="http://localhost:8080" HTTPS_PROXY="https://localhost:8080" s5cmd ---no-verify-ssl ls
2018/10/11 12:58:27  s3://some-bucket
```

Please let us know if this helps.
