### ISSUE TITLE
how to don't print cp record of each file when using sync?

### ISSUE THREAD

**Issue by bingwork** [peak/s5cmd#669]
hi, s5cmd is really great. I have a small question, when I sync 1K images to s3, it records all cp log of each image like bloew

cp s3://sagemaker-us-west-2-798908321432/blip-flickr/sub-images/973353650.jpg /tmp/flickr-data/flickr30k-images/973353650.jpg
cp s3://sagemaker-us-west-2-798908321432/blip-flickr/sub-images/974924582.jpg /tmp/flickr-data/flickr30k-images/974924582.jpg

how to set don't print them?
like aws s3 sync /path/to/directory s3://bucket/folder --no-progress

thanks.
@igungor

**Comment by denizsurmeli** [comment]
Hi, we currently don't support that, but you can redirect the output by `s5cmd sync s3://bucket1 s3://bucket2 > /dev/null`

**Comment by igungor** [comment]
@bingwork You may use `--log=error` global flag to only print errors.
