### ISSUE TITLE
recursive du

### ISSUE THREAD

**Issue by ixodie** [peak/s5cmd#685]
Thinking about usability for this...

I would want to manually verify the number of objects and the total size of all objects in the bucket, to correlate with a local 

Similiar to the output of this command:

find . | wc -l

**Comment by ilkinulas** [comment]
You can use wildcards with the `du` command just like `ls` command.

```shell
➜  s5cmd ls 's3://my_bucket/ilkin/*'
2024/06/28 15:40:21              1750  go.mod
2024/06/28 15:41:32              1750  go.mod_2
2024/06/28 15:57:25              1750  test/go.mod
2024/06/28 15:57:27              1750  test2/go.mod
2024/06/28 15:57:31              1750  test2/test1/go.mod

➜  s5cmd du  's3://my_bucket/ilkin/*'
8750 bytes in 5 objects: s3://my_bucket/ilkin/*
```
