### ISSUE TITLE
Remove operation on non-existent file return success

### ISSUE THREAD

**Issue by igungor** [peak/s5cmd#69]
```
tmp  Δ aws s3 ls 's3://bucket/notfound'
tmp  Δ echo $?
1
tmp  Δ s5cmd rm 's3://bucket/notfound'
2020/02/25 13:08:38 +OK "rm s3://bucket/notfound"
tmp  Δ echo $?
0
tmp  Δ
```

Removing a non-existent object returns `0` exit code. Also the log is misleading. It says worker is finished successfully but we're not interested in that actually.

I expect the status code a non-zero value. Also I don't need an `+OK` log cause it's not what it says.

**Comment by igungor** [comment]
It turns out AWS SDK doesn't report if the given object is missing or not. If we want to support this feature, we need to send a HeadObject request for each key. That'd be a lot of requests for batch mode.

Closing as WONTFIX.

**Comment by igungor** [comment]
Well, we already report the error if the given object key has a glob. If a glob is given, `s5cmd` expands the glob by doing a pagination for given prefix, so we know that if the prefix has any object in it. We know for sure that objects with globs are handled correctly and errors are reported.

The problem is, if the input is a full S3 URL (no glob characters in it), sending DeleteObject request returns 200 and we don't know if the given object exists. Since this is a non-batch operation, we can send HeadObject requests and the overhead would be negligible. I think we can (and should) implement it. 🤷‍♀

**Comment by ilkinulas** [comment]
Keeping the existing behavior. Exit code 0 is the expected return code.
