### ISSUE TITLE
Unexpected subdirectory structure when running cp

### ISSUE THREAD

**Issue by agonzalezv** [peak/s5cmd#70]
I'm running: 

`AWS_REGION=my-region /home/ubuntu/go/bin/s5cmd cp -u -s --parents s3://my-bucket/my-subdirectory/.local/* /home/ubuntu/.local/`

I'm expecting the contents from `.local` inside my subdirectory to be copied into `/home/ubuntu/.local/`, instead, they are getting copied to `/home/ubuntu/.local/my-subdirectory/.local`

Is this an expected behaviour? as per the [command option documentation](https://github.com/peak/s5cmd#command-options), the dir structure is created from the first wildcard onwards, and I recall it working like that in previous versions of `s5cmd`

Please advise

**Comment by igungor** [comment]
Which `s5cmd` version are you using?

**Comment by agonzalezv** [comment]
`s5cmd version v0.7.0`

**Comment by igungor** [comment]
I couldn't reproduce the issue on macOS with a similar folder hiearchy as yours. Could you prepare a repro? Either a public bucket/prefix or a step by step reproduce (upload file 1, file 2 and download them) would help.

**Comment by agonzalezv** [comment]
Thank you for the prompt response Ibrahim, I'll get that done as soon as I have a minute and I'll come back to you

**Comment by agonzalezv** [comment]
@igungor please try the following dockerfile : 

```
FROM ubuntu:18.04

WORKDIR /home/ubuntu

ENV AWS_ACCESS_KEY_ID your-access-key-id
ENV AWS_SECRET_ACCESS_KEY your-aws-secret-key
ENV AWS_REGION ap-southeast-2
ENV S3_BUCKET s5cmd-tester

RUN apt-get update --fix-missing && \
    apt-get install -y software-properties-common && \
    rm -rf /var/lib/apt/lists/*

RUN add-apt-repository ppa:longsleep/golang-backports && \
		apt install unzip curl git golang-go -y

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
		&& unzip awscliv2.zip \
		&& ./aws/install \
		&& aws configure set default.region $AWS_REGION \
		&& aws configure set default.s3.max_concurrent_requests 500 \
		&& aws configure set default.s3.max_queue_size 1000

RUN export GOCACHE=/home/ubuntu/.cache/go-build && \
		export GOPATH=/home/ubuntu/go && \
		go get -u github.com/peak/s5cmd && \
		AWS_REGION=$AWS_REGION AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY /home/ubuntu/go/bin/s5cmd cp -u -s --parents s3://$S3_BUCKET/config/.local/* /home/ubuntu/.local/ >> /tmp/node-sync.log
```

you will have to replace `your-access-key-id` and `your-aws-secret-key` by actual credentials for it to work, when you spin that container and list the contents of `/home/ubuntu/`, you will see that `folder1` and `folder2` are getting copied into `.local/config/.local/` instead of just `.local`

Let me know if you have any issue connecting to that bucket

**Comment by igungor** [comment]
@agonzalezv thanks a lot! I'll try the repro and see what's going on.

**Comment by igungor** [comment]
> s5cmd version v0.7.0

I can confirm that `master` has an issue but v0.7.0 works for me. Do you confirm that `v0.7.0` works for you too?

Please use released versions instead of compiling from `master`. We'll land a fix on master branch and cut a release once it's ready.

**Comment by igungor** [comment]
@agonzalezv Could you test from master branch please? If the problem still persists, we can open the issue.

Also as I mentioned from previous comment, please keep using the latest release, not from master. Master branch is a work on progress and things may break.

**Comment by agonzalezv** [comment]
@igungor That's great to know, I'll retest and report as soon as I can

**Comment by agonzalezv** [comment]
After re-running the container above and, I get this when trying to get the version :

```
root@ad599d9:/home/ubuntu/go/bin# /home/ubuntu/go/bin/s5cmd -version
Usage: /home/ubuntu/go/bin/s5cmd [OPTION]... [COMMAND [PARAMS...]]

Options:
  -cmp-install
    	Install shell completion
        [ ...more below ]
Commands:
    !, batch-rm, cp, du, exit, get, ls, mv, rm

To get help on a specific command, run "/home/ubuntu/go/bin/s5cmd <command> -h"
2020/02/27 22:49:22 no command file nor a command specified
```

Is that the right way to get the version or I'm missing something?

**Comment by agonzalezv** [comment]
Update #2: Your fix works!. Now I'm seeing `folder1` and `folder2` inside `.local`, as expected. Thank you for your help! @igungor

**Comment by igungor** [comment]
> Is that the right way to get the version or I'm missing something?

That is the right way. Flag parsing logic got a hiccup during a refactor. I just fixed it.

**Comment by igungor** [comment]
> Update 2: Your fix works!. Now I'm seeing `folder1` and `folder2` inside `.local`, as expected. Thank you for your help! @igungor

Cool. Glad to know. Thanks for your help.
