### ISSUE TITLE
README.md incorrect example "you can compress the data before uploading"

### ISSUE THREAD

**Issue by PerMildner** [peak/s5cmd#704]
https://github.com/peak/s5cmd/blob/c1c7ee35acfc16aaf4a2b060129aa60b75bb5ef5/README.md?plain=1#L269

says:
> Or you can compress the data before uploading:
> 
>     tar -cf - file.bin | s5cmd pipe s3://bucket/file.bin.tar

But `tar -cf - file.bin` does not compress anything.

**Comment by ahmethakanbesel** [comment]
Hello,

Thanks for the correction. Here is the updated example. 
I will create a PR for updating the README file as soon as possible.

```
tar -czf - file.bin | s5cmd pipe s3://bucket/file.bin.tar.gz
```

**Comment by ahmethakanbesel** [comment]
Hi,

Thanks for pointing that out.
An example like the one below could be more appropriate.

```bash
tar -czf - file.bin | s5cmd pipe s3://bucket/file.bin.tar.gz
```
