### ISSUE TITLE
sync command copies a new object everytime when the s3 version is on GLACIER

### ISSUE THREAD

**Issue by stevenmcastano** [peak/s5cmd#712]
I'm running version `v2.2.2-48f7e59` and when I add the `--storage-class 'GLACIER'` option to my command line, it does properly put the object in Glacier, but then subsequent sync commands fail to detect that version as the same as the one being on disk and subsequent runs just copy a new version over and over again.

This really defeats the purpose for me... I'm trying to upload backups of a large photo library to use as a cloud backup from my NAS. So there is rarely if ever a need to download everything, but I do... at times... update a few files here and there, mostly just adding files to an already existing directory... so this makes it impossible for me to write a script that executes via cron once a night to upload my backups.

**Comment by jesanfafon** [comment]
Not sure if this is the same issue precisely or not, but I'm still showing files being copied in a `--dry-run` of `sync` on 2.3.0 even though they exist in the target s3 bucket. Going to run the command for real and see if the behavior matches `--dry-run` or not.

**Comment by 4o4x** [comment]
@jesanfafon 
I have tried it several time after your comment. It seems like there is no issue.

> Going to run the command for real

Did you run ?

**Comment by jesanfafon** [comment]
> I have tried it several time after your comment. It seems like there is no issue.

Yes, I ran it again. It worked. I suspect the session I was in had the old executable cached, or there was something subtly wrong with the command I was running.

False alarm!
