### ISSUE TITLE
"Beast mode" example is incorrect

### ISSUE THREAD

**Issue by PerMildner** [peak/s5cmd#714]
https://github.com/peak/s5cmd/blob/c1c7ee35acfc16aaf4a2b060129aa60b75bb5ef5/README.md?plain=1#L734

The title should presumably be "Batch mode s5cmd" not "Beast mode s5cmd".

The example is not correct:

> BUCKET=s5cmd-test; s5cmd ls s3://$BUCKET/*test | grep -v DIR | awk ‘{print $NF}’
> | xargs -I {} echo “cp s3://$BUCKET/{} /local/directory/” | s5cmd run

This will not work if any file name listed by `s5cmd ls` contains white space (or other "funny" chars) in its name, because:
1. `awk ‘{print $NF}’` will then only extract some suffix of the file name (since a white space in the file name would be used by `awk` as a field delimiter).
2. Even if the file name extraction from the result of `s5cmd ls` was corrected, the resulting input to `s5cmd run` would most likely not work (also see issue #713).

**Comment by ilkinulas** [comment]
please create a pull request if you think that the example is misleading.
