### ISSUE TITLE
Support glob character in destination object?

### ISSUE THREAD

**Issue by dprestegard** [peak/s5cmd#724]
Hello!

I'm using s5cmd for a use case where objects have pretty wacky names, including `?` and `*`. Don't ask me why! :)

I use command files, and unfortunately if I'm trying to download these objects via command file I run into the following error:

```
target "/var/tmp/sample file name ?.wav" can not contain glob characters
```

Is there any way to make s5cmd relax this requirement so I can actually download these objects via a command file?

I already wrap source and destination paths in double quotes to handle spaces.

**Comment by dprestegard** [comment]
Any word on this?

**Comment by igungor** [comment]
Hello,

We have `--raw` flag for `cp` subcommand. It may help your use case.

```
--raw                          disable the wildcard operations, useful with filenames that contains glob characters (default: false)
```

**Comment by dprestegard** [comment]
Thanks. I made a PR to mention this in the readme :) https://github.com/peak/s5cmd/pull/781

**Comment by igungor** [comment]
Thanks!
