### ISSUE TITLE
Missing release for pypi for latest version

### ISSUE THREAD

**Issue by tchaton** [peak/s5cmd#747]
```
(.venv) ➜  litdata git:(reduce_uploaders) pip install -U s5cmd
Requirement already satisfied: s5cmd in ./.venv/lib/python3.9/site-packages (0.2.0)
```

**Comment by seruman** [comment]
Hi, pip packaging is not maintained by us. I see that the homepage link in https://pypi.org/project/s5cmd/ points to
https://github.com/ImagingDataCommons/s5cmd-python-distributions
