### ISSUE TITLE
s5cmd head - ERROR "head": command not found

### ISSUE THREAD

**Issue by yitzhaklevi** [peak/s5cmd#763]
Hey, Thank you very much for implementing my feature request (https://github.com/peak/s5cmd/issues/682)
Couple of issues:
- README.md has example of usage (https://github.com/peak/s5cmd?tab=readme-ov-file#check-if-a-bucket-exists) but the --help wasn't updated with the new command (https://github.com/peak/s5cmd?tab=readme-ov-file#features)
- can't use s5cmd head (tried using the build from peakcom/s5cmd docker and conda-forge (2.2.2)) - if it's not supported yet it should be removed from the README.md or specified in which builds it's supported.

Thanks !

**Comment by kucukaslan** [comment]
Some of the changes in the master have not been officially released unfortunately. 

You may try building from source yourself to use head command
https://github.com/peak/s5cmd?tab=readme-ov-file#build-from-source

**Comment by 4o4x** [comment]
Hi, new release has been published. You can use head command with new release. [Check ](https://github.com/peak/s5cmd/releases/tag/v2.3.0) it out.
