### ISSUE TITLE
Any newer release planned?

### ISSUE THREAD

**Issue by adityak-sysdig** [peak/s5cmd#766]
Hi team,

We are using S5CMD for our S3-related operations and I was wondering whether we plan to support go v1.21 and newer versions as well as any roadmap for newer release of the binary as the latest stable release available was released more than a year ago.

Requesting for a newer release version with newer features (if any) as well as updates to go version being used.

Regards.

**Comment by TomHellier** [comment]
Hi @igungor  - There are 18 vulnerabilities in s5cmd because it is using a really old version of go, @lizzzcai updated the build to run go 1.23 in #764 , please can you perform a new release?
