### ISSUE TITLE
Please create a new official release

### ISSUE THREAD

**Issue by gkowarzyk** [peak/s5cmd#777]
Hello,

As explained in Issue #717 (dated April 24), it would be very helpful for us if a new official release (with binaries) is created.
It would help as much for patching vulnerabilities as for sorting out some license issues.

There are other issues where other people also show interest in a new release being creaged (e.g. Issue #766, #764).

Thanks in advance!

**Comment by 4o4x** [comment]
Hi, new release has been published. [Check ](https://github.com/peak/s5cmd/releases/tag/v2.3.0) it out.

**Comment by gkowarzyk** [comment]
This is awesome, thanks!
