### ISSUE TITLE
Upload happens despite condition checks failing.

### ISSUE THREAD

**Issue by s4mur4i** [peak/s5cmd#91]
When giving a user following permissions:
PutObject
GetBucketLocation

And trying to upload with -n -s -u options there are no errors, and upload just happens:
```
s5cmd cp -n -s -u  test s3://test/test/
                    # Uploading test... (1 bytes)
2020/03/09 16:16:51 +OK "cp krisz-test s3://test/test/test"
 s5cmd cp -n -s -u  krisz-test s3://test/test/
                    # Uploading test... (1 bytes)
2020/03/09 16:18:23 +OK "cp test s3://test/test/test"
```
According to job_check:
https://github.com/peak/s5cmd/blob/e074b96d52e152bc7361086fa9ae4407359753b2/core/job_check.go#L14
We should fail because we get an error from HeadObject not having permission, but it just assumes the file is not present.
Also when giving Permission only to ListBucket and doing same operation on cloudtrail event is generated for accessdenied for headobject, but no error is thrown.

**Comment by igungor** [comment]
Hey @s4mur4i, do you reproduce the same issue with the `master` branch?

**Comment by igungor** [comment]
Ping @s4mur4i.

**Comment by s4mur4i** [comment]
on master it works, tested. we can close the case.
