### ISSUE TITLE
The authorization header is malformed

### ISSUE THREAD

**Issue by TirthankarMukherjee** [peak/s5cmd#93]
`ERROR "AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' status code: 400, request id: 21F0039B......, host id: 8JtyS7dK5tOHL2owqHw6kKtpvD.........+c=" %!v(MISSING)`

I am trying to run this command `AWS_REGION=us-west-2 s5cmd cp ..` inside a Kubernetes pod, but getting above error, though aws configure is correctly set and keys are in env variables. Any suggestion what may be doing wrong.
s5cmd version = v0.7.0-2a123c

Note - Just noticed the `ls` command works fine though

**Comment by igungor** [comment]
Hey @TirthankarMukherjee, just pushed a fix to `master` branch. Could you try and see if the fix works for you please?

**Comment by TirthankarMukherjee** [comment]
@igungor Yes, it is working for me. Thank you so much !
